### ISSUE TITLE
Kodi hangs when playing episode from library

### ISSUE THREAD

**Issue by juanma-cvega** [jurialmunkey/plugin.video.themoviedb.helper#325] opened 2020-10-27 14:05 UTC
I reimported my TV shows lists using the library integration just in case it was a problem with the files not working after the update but it still hangs. It seems as if it was trying to play a local file directly because I can see in the corner what I think is the finish time of the episode but then it just stops there. 
If I play the episode directly from the addon it works fine. I have set up a default player, in my case Venom. 
I can provide a debug log if you need it once I get back home.

**Comment by jurialmunkey** [comment] 2020-10-27 14:12
Yes please debug log would be useful. Play via strm from library works fine for me.

**Comment by matusaurio** [comment] 2020-10-27 21:31
I'm also having the same problem here, Kodi freezes when trying to play an episode from the library

Here's the log: [https://paste.kodi.tv/xihiterige](url)

**Comment by jurialmunkey** [comment] 2020-10-28 01:29
Thanks for the log.

Can you test the version in the "testing" branch and if it still fails can you grab me the log from that (I added some extra logging there that will help me locate where it is failing).

**Comment by jurialmunkey** [comment] 2020-10-28 01:31
Sorry wait one second. There's an error

**Comment by jurialmunkey** [comment] 2020-10-28 02:01
Okay, now can you test the version in the [testing branch](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/testing.zip) and if it still fails can you grab me the log from that (I added some extra logging there that will help me locate where it is failing).

**Comment by juanma-cvega** [comment] 2020-10-28 13:05
I just tested it with your testing branch and it seems to work now. It does something odd however I think it didn't do before. I have Kodi set up to adapt the display framerate to the video one. It seems when I play a video from the library as if it was doing just that as I see the screen flash black before the addon the default player is configured with takes over. It's kind of weird as at that point there is no video playing, just a call to another addon, so it cannot know what to change the framerate to. If I play a video from within the addon instead of from the library it doesn't do that. It doesn't freeze Kodi though so feel free to close the issue if you consider it's not related.

**Comment by matusaurio** [comment] 2020-10-28 16:59
Here is the log with the testing branch installed: [https://paste.kodi.tv/yalepiwiza](url)
I'm also experiencing similar behaviour like @juanma-cvega

**Comment by jurialmunkey** [comment] 2020-10-28 22:44
The black screen flash is because it resolves to a dummy file first which I quickly stop. 

Kodi forces strms to need to resolve to a file. The issue is that we don't know if the plugin we call is going to resolve (because there's so many different methods) so I need to use a short video and stop it. Otherwise kodi will keep trying to replay because it thinks it fails. 

The old method I used to used was to pass an empty listitem to the resolve method but then kodi starts constantly complaining in the log that no video file is playing and the constant error writing is not great. Really strms are not suited to this type of plugin and I'm just hacking them into working.

**Comment by juanma-cvega** [comment] 2020-10-29 08:19
Ok, understood. So in the end there is no other way around this. Either error logs or this small video workaround. In any case I'd say the issue is resolved, library integration works for me now. The only thing I still don't get is why it didn't freeze for you and other people. It looks like something that should have been broken for everyone.

**Comment by jurialmunkey** [comment] 2020-10-29 13:53
> 
> 
> The only thing I still don't get is why it didn't freeze for you and other people. It looks like something that should have been broken for everyone.

Differences between OSes and even skins. I got crash reports for Aura before when everything was working perfectly fine for me in Arctic Horizon and Estuary. 

@juanma-cvega @matusaurio 
Could you both test the latest changes I've made to the testing branch. I'm trying out actually resolving the URL and it seems to work pretty well for a lot of plugins. TMDbHelper will prompt to ask which method you want to use - the new setResolvedURL or the old PlayMedia - so you can revert to using PlayMedia for certain players if the new setResolvedURL method doesn't work. 

Advantage of setResolvedURL approach is that avoids the need for hacks like resolving to a dummy file. It will also allow Kodi to save the resume point and watched flags natively, and also should make playlists work much more nicely. The obvious downside is that for some players that don't resolve directly to a playable file it either won't work at all or will behave oddly.

Once you know which method works for you for a particular player, you can then override the dialog prompt by adding `"is_resolvable": "true|false"` to the player file (true for using setResolvedURL automatically, and false for using PlayMedia) - see bundled Netflix and Youtube players for example.

**Comment by juanma-cvega** [comment] 2020-10-29 20:03
I just tested it and I have a question. Is there any change to the old way of playing videos? Because I tried using the new setResolvedURL and it works but the screen still changes its framerate while using the old method it doesn't happen anymore and still works.

**Comment by jurialmunkey** [comment] 2020-10-29 23:45
> 
> 
> I just tested it and I have a question. Is there any change to the old way of playing videos? Because I tried using the new setResolvedURL and it works but the screen still changes its framerate while using the old method it doesn't happen anymore and still works.

By "old" way, I mean that PlayMedia is the _very_ old way used in the earliest versions. In v3 I was for the most part instead passing the end url to `xbmc.Player().play()` which served as mid-way catch-all point between PlayMedia and setResolvedURL to try to deal with all the different approaches that different plugins would use. 

Basically:

- setResolvedURL 
   - PROS: No hacks involved. Kodi sets watched natively. Allows merging listitem metadata with the playable url.
   - CONS: If the end plugin doesn't also use this method then it can behave unpredictably in certain scenarios.
- PlayMedia
   - PROS: Plays everything. Works every time because it simply just plays the path it is given.
   - CONS: For strm we need to use dummy resolve hack so Kodi won't bug us about failing to find the next item to play. No merging of metadata so end plugins that only provide a raw url won't get artwork or info.
- xbmc.Player()
   - PROS: Allows merging metadata and can play everything.
   - CONS: Least preferred method. Still needs a dummy url resolved for strm. Needs playermonitor tricks to set watched. Least stable approach because it relies on a lot of hacks and tricks to work in all cases.

The framerate switch probably isn't happening with PlayMedia because I'm first setting the dummy video file and stopping it. My guess would be that because the file plays and is stopped so quickly, Kodi probably suppresses the frame rate switch to avoid switching multiple times in rapid succession. There wasn't this issue in v3 because I didn't call the dummy video - I just used an empty listitem instead (but that approach has the log spam player exception problem I mentioned previously).

**Comment by matusaurio** [comment] 2020-10-30 15:53
Sorry for the late answer, I tried and both methods are working. 
The first time the dialogue prompt showed, after selecting setResolvedURL, Kodi froze but after restarting the app and playing again a file it worked.
If you are interested, here is the log with both methods working: https://paste.kodi.tv/ehoketifoq 

Thank you for your help

**Comment by jurialmunkey** [comment] 2020-10-31 04:39
Excellent! Thanks so much for testing 😁 

I've now merged the testing branch into master. I've also added a GUI configuration option for players in the TMDbHelper addon settings.

In the configuration dialog you can change Name, Plugin Priority (changes rank of plugin in player select dialog), and Resolve Method for all players. You can also Disable/Enable plugins.

TMDbHelper will save any changes in the "reconfigured_players" folder in its addon_data folder - basically it saves a copy of the player with the changes added. Any player in this folder will then override players with the same name found elsewhere. So to reset to defaults you just delete the copy found in the reconfigured_players folder as the player in the main folder is left intact (this is exactly what the "reset to defaults" option in the configuration dialog does).

Options to set fallbacks via the GUI will also be coming soon (you'll notice in the fifth position in the configuration dialog for a player is blank - this is the place holder for where the fallback options will go).

**Closed by jurialmunkey** 2020-10-31 04:39 UTC

**Comment by daveftw84** [comment] 2023-09-19 08:03
> The black screen flash is because it resolves to a dummy file first which I quickly stop.
> 
> Kodi forces strms to need to resolve to a file. The issue is that we don't know if the plugin we call is going to resolve (because there's so many different methods) so I need to use a short video and stop it. Otherwise kodi will keep trying to replay because it thinks it fails.
> 
> The old method I used to used was to pass an empty listitem to the resolve method but then kodi starts constantly complaining in the log that no video file is playing and the constant error writing is not great. Really strms are not suited to this type of plugin and I'm just hacking them into working.

mine wont play the dummy video no matter what i do, reinstalled, wiped settings, etc
