### ISSUE TITLE
[Feature Request] 'Play random episode' in context menu from widgets

### ISSUE THREAD

**Issue by coopers-htpc** [jurialmunkey/plugin.video.themoviedb.helper#514] opened 2021-06-23 00:00 UTC
I'm using Kodi 19, Aura Mod, Seren, The Crew, TMDB Helper, and a small amount of local content.
I like pointing my widgets to TMDB Helper items, because if I have the content locally then it will play that instead of using an add-on.
If I have a widget pointing to a Seren item, then I can use the context menu to choose 'play random episode'.
I'd love to have that feature available with my TMDB Helper widgets.

**Comment by jurialmunkey** [comment] 2021-07-07 00:35
Duplicate of this request: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/423

Option will come soon. Closing this issue to keep things in the one thread.

**Closed as completed by jurialmunkey** 2021-07-07 00:35 UTC
