### ISSUE TITLE
[Bug] Trakt List Sorting

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/plugin.video.themoviedb.helper#140] opened 2020-03-28 15:20 UTC
I've noticed this weekend that the default sorting doesn't seem to be being applied to Trakt lists in the add-on.

This is the [Star Wars](https://trakt.tv/users/draackje/lists/star-wars?sort=released,desc) list by @draackje, which is sorted with "Release Date, Ascending" by default on the website:
![image](https://user-images.githubusercontent.com/2319508/77826296-c42a4d00-70cb-11ea-8173-f094092f863d.png)

This one is [Disney Animated Classics](https://trakt.tv/users/draackje/lists/disney-animated-classics?sort=released,desc), also sorted by "Release Date, Ascending", but in Kodi it appears to be sorted in descending order (and obviously not showing all of the items):
![image](https://user-images.githubusercontent.com/2319508/77826411-53376500-70cc-11ea-901b-d01f18d03819.png)

This same thing appears to happen with my personal lists as well.

**Comment by jurialmunkey** [comment] 2020-03-29 02:28
Duplicate of this issue: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/89

Trakt doesn't provide sorting methods via API. The Trakt API sorts all lists by item rank.
You can see the API endpoint here:
https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-custom-list

The only other top level key available to sort by is `listed_at`. That is the date the item was added to the list. I use that to sort the lists because at least it is better than rank because at least newly added items aren't buried. 

Other values are only possible to sort by if I pull extended info from Trakt, when means longer loading times.

**Comment by drinfernoo** [comment] 2020-03-29 02:30
I'm probably in the minority, but I'd take the longer loading for a faithfully sorted list... I do see the dilemma, though 🤔

**Comment by jurialmunkey** [comment] 2020-03-29 02:32
The other issue is that you need to know the sort method before the list loads. I can get the default sort from the headers, but it isn't possible to then change the sort method.

**Comment by drinfernoo** [comment] 2020-03-29 02:43
I'm not hoping to be able to change the sort... just to have the default sort that is set on the website for whatever list. That makes sense, right?

**Comment by jurialmunkey** [comment] 2020-03-29 03:35
@drinfernoo - Okay, can you test latest (v2.2.90)? I think I have it working properly now - doesn't seem to add too much overhead cost to get extended info (after first time load, it is cached anyway).

I wasn't able to do all the sort methods Trakt lists: I couldn't do `my_rating`, `watched` or `collected` because these all involve additional look-ups that are probably not worth the effort.

I think sort by release date will only work for movies because there isn't a "release" field for shows. Shows have first aired instead and it's a pain to do if conditionals in the lambda function for python's sorted() method.

Also, popularity score doesn't seem to be exposed - it's supposed to be a weighted score based on number of likes and comments. Trakt API is only showing number of comments, so that's what I'm sorting by for popularity.

These sort methods should all work (asterisks for comments above) - rank, added, title, released, runtime*, popularity*, percentage, votes, random

**Comment by jurialmunkey** [comment] 2020-03-30 06:50
@drinfernoo - Just wondering if you got the chance to test and confirm that the lists were now being sorted correctly? Seems to be working fine on my end but would be good to have someone else test.

**Comment by jurialmunkey** [comment] 2020-04-03 23:15
It seems to be working correctly, so I'm going to close the issue.

**Closed by jurialmunkey** 2020-04-03 23:15 UTC
Labels: enhancement
