### ISSUE TITLE
Detailed Information at List level

### ISSUE THREAD

**Issue by skyfsza** [jurialmunkey/plugin.video.themoviedb.helper#13] opened 2019-12-01 07:44 UTC
Currently it seems that I am only getting detailed Infolabels (MPAA, Ratings etc) when I enter into a TV show / Movie and not at the parent list level. 

Is it possible to add a settings option which enables "detailed" information at the top level when browsing in TMDBhelper?

**Comment by jurialmunkey** [comment] 2019-12-01 08:34
It's possible but I don't want to as it makes the plugin significantly slower. 

To get a list from TMDb requires one API request. Getting detailed information requires making an additional request for every single individual item. So for a list of 25 items that is at least 25 requests.

TMDb caps requests at 4 per second. For a list of 25, that will take 6.5 seconds. 
If you have 10 widgets, that's more than a minute loading time, which is a massive difference compared to less than 10 seconds currently.

Also, if you have OMDb enabled, that is rate limited to 1 request per second with a cap of 1000 per day. 10 widgets of 25 items and you are already a quarter of the way to your daily limit. Plus, with the additional rate limiting, the time is extended x4, taking it to approx 5 minute loading time.

Perhaps more importantly than all of this, is that it will result in a massive increase in the number of requests I'm making overall - which is the reason why SkinHelper had to be heavily rate limited and required a personal TMDb apikey. I'd rather keep things quick and respect the APIs that I'm using.

**Comment by jurialmunkey** [comment] 2019-12-01 08:39
BTW - if you have entered into the detailed item, its information will be cached and the plugin will use it in all lists.

**Comment by skyfsza** [comment] 2019-12-01 08:41
Thanks for the feedback.

That makes sense, will stick with skinhelper at the "list" level for info that is missing.

Thanks!

**Comment by skyfsza** [comment] 2020-03-04 09:45
Apologies upfront if i'm asking a stupid question :)

As per the above, when you "browse" into a TV Show / Movie, the detailed information is fetched and cached, next time you are at the "list" level,  detailed info will be available in the infolabels for that item.

When using the Service Monitor, at the list level the "detailed" information is pulled for the focused TV/Movie item and cached - much like browsing into the TV/Movie item.  

Is it possible to have the detailed info that is pulled/cached from Service monitor also be added to the infolabels for that item? Eg, making service monitor act in the same way as browsing into the item.

**Comment by jurialmunkey** [comment] 2020-03-06 10:36
> 
> As per the above, when you "browse" into a TV Show / Movie, the detailed information is fetched and cached, next time you are at the "list" level, detailed info will be available in the infolabels for that item.

Yes, that's correct - if the default action in the addon is set to "browse" and you click into a movie/tvshow/episode then the details of the item are cached. The cached details are then added to the listitem when the list is next loaded (just pressing back from the details won't reload the list because Kodi keeps the previous list in memory for quick navigation back).


> 
> When using the Service Monitor, at the list level the "detailed" information is pulled for the focused TV/Movie item and cached - much like browsing into the TV/Movie item.

Yes, that's correct.


> 
> Is it possible to have the detailed info that is pulled/cached from Service monitor also be added to the infolabels for that item? Eg, making service monitor act in the same way as browsing into the item.

No. As soon as the list is loaded the plugin exits and no longer has any control over the list. The list items need to be created before the list displays.

Basically plugin list containers are created like so:

- Kodi calls a new independent instance of the plugin (which is just a normal python script).
- The plugin is given the url in the `<content>` tags and a directory handle number.
- The plugin retrieves the relevant data from the APIs
- The plugin then creates ListItem objects from that data
- The plugin then tells Kodi to associate those ListItem objects with the directory handle.
- The plugin then tells Kodi it has finished making ListItems.
- The plugin exits.
- Kodi then fills the list container using the objects associated with the container's directory handle.

So the issue is that the service monitor doesn't have access to the directory handle or the listitem objects because it is a separate instance, so it can't modify those objects - only the plugin instance used to create the directory can do that but it needs to exit for Kodi to create the list.

Even if it was possible to access the ListItems, you can't modify them after they've been created. You either need to reload the list or remove the object and re-add it. Both approaches would be very disruptive - either busy loader every time you move items or items dropping in and out of the list.

If modifying the listitem properties was a possibility, I would do it - the only reason window properties are used by the service monitor is because that's the only possible way to make the info easily accessible to the skin.

**Comment by skyfsza** [comment] 2020-03-06 14:59
Thanks for the detailed response.

Poorly worded from me, but yes fully understand that this would all be after the next container refresh / widget reload, not live (as great as that would be!) 

"The next time the list is loaded it will use the info that was cached from the service monitor. However, it is not possible to edit the listitems in a list "live". ListItems need to be created before the list is displayed."

This is the part that doesn't seem to work for me. I open a list in a library view, get ratings via Service Monitor for the focused movie, do a container refresh (or back out and re enter the list) and the ListItem.Property rating for the movie is still empty.

I just did a bit more testing and it seems the issue is limited to TMDB based lists, the cached info gets added correctly on trakt based.
 
Quick video example showing TMDB list vs Trakt
https://imgur.com/a/olgI7zi

Thanks!

**Comment by jurialmunkey** [comment] 2020-03-07 05:58
> This is the part that doesn't seem to work for me. I open a list in a library view, get ratings via Service Monitor for the focused movie, do a container refresh (or back out and re enter the list) and the ListItem.Property rating for the movie is still empty.

Hmm yeah only TMDb cached details are being added. Not OMDb cached details. I'll look into it

**Comment by jurialmunkey** [comment] 2020-03-07 06:11
@skyfsza - Okay I think this bug where cached OMDb data wasn't being added should be fixed now.

--- 
Relevant Commit: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/96b7850fe42638869c7f9713adc356b42769ef29

**Comment by skyfsza** [comment] 2020-03-07 07:18
Looks good on the latest release, getting OMDb data cached on TMDB list now.

Thanks for the quick fix!

**Comment by jurialmunkey** [comment] 2020-03-07 08:43
No worries! I'm surprised I didn't realise this was happening. Shows how much I rely on the service monitor!

**Closed by jurialmunkey** 2020-03-07 08:43 UTC

**Comment by skyfsza** [comment] 2020-03-07 08:59
In prep for kodi 19 trying to get rid of Skinhelper from the skin, Service monitor is helping me to take a big step that way :)

Side question/issue if you get a chance.  

Service Monitor does not appear to clear values when you move on to the next item in the list, which causes the old/previous value to show until the new value is fetched.  

I have added a visibility condition to check String.IsEmpty(Window(Home).Property(TMDbHelper.IsUpdating)), but adding this to each and every SM variable/control doesnt feel like the right way to do things?

Am I missing something?

**Comment by jurialmunkey** [comment] 2020-03-07 11:26
It only clears if there are no details retrieved or on scroll but it doesn't bother when just moving to the next item because it's not worth the performance hit. I also found that clearing the properties every time caused other issues where the properties wouldn't get set at all.

I'm not completely certain but I think Kodi sets/clears window properties in a background thread rather than making the script wait. That's good most of the time but when you're setting and clearing a lot of properties at once, you can end up with race conditions where the property that was just set is cleared because the clearing thread lagged behind - I think that's what happens when I clear the properties first.

Also, it is very heavy on performance to clear first. If you look at the properties available to the detailed item, there's 100s of properties to set (just cast/crew alone is going to be more than 100). If we have 250 properties to set, then that's also 250 properties to clear. It is significantly better performance wise to just set one property that says the script is updating and use that as a visibility condition. And once the data is cached, it is practically instant for the properties to update a lot of the time (at least that's been my experience).

**Comment by skyfsza** [comment] 2020-03-08 10:33
Makes total sense, probably one (of many) reasons SkinHelper gives the performance hit it does.

Thanks again for detailed response!

**Comment by skyfsza** [comment] 2020-03-22 11:34
Found another potential Service Monitor issue, not sure if its a bug or just a bad use case.

I am filling dynamic list containers in DialogVideoInfo for additional content such as cast, similar, recommended etc.

The widget containers set the WidgetID, which I am seeing correctly change for Window(Home).Property(TMDbHelper.WidgetContainer), however if I check any of the Window(Home).Property(TMDbHelper.ListItem.x)  infolabels, the returned value is for the movie/show/episode DialogVideoInfo is opened for. 

Example:
DialogVideoInfo opened on "Better Call Saul"
Container 53003 content filled with plugin://plugin.video.themoviedb.helper/?info=similar

Infolabels returned with container 53003 focused:
ListItem.Title: Better Call Saul
Container(53003).ListItem.Title:  Boston Legal
Window(Home).Property(TMDbHelper.ListItem.Title): Better Call Saul
Window(Home).Property(TMDbHelper.WidgetContainer): 53003

**Comment by jurialmunkey** [comment] 2020-03-22 13:35
Yeah, the video info dialog overrides the widget container settings. If you changed the container then you would lose other info relevant to the main item like widgets or poster etc. 

Also, consider the following scenario: you have a widget ID 3001 and widgetcontainer set to 3001. Then you open videoinfo dialog and you suddenly lose your service monitor data because 3001 doesn't exist in the dialog (which is not what you'd want).

I think the way it is makes the most sense, but it could be possible to write a simple workaround to disable the check for videoinfo dialog and force check the container ID always. Is it something you desperately need or more just something you noticed?

**Comment by skyfsza** [comment] 2020-03-22 13:54
Makes sense.  In my particular use case wouldnt cause an issue (widgets are not visible when main video info details are, like your AZ2 scroll down) but I definitely see as a standard practice how it could cause problems.

I actually only have one use for SM in video info and thats getting Bio info for a cast list.  Looking to have the cast widget with an Info section below displaying the ListItem.Property(biography).

Would it slow the cast list down by much if you add in Biography at the list level?

**Comment by jurialmunkey** [comment] 2020-03-22 20:53
Yeah bio would slow things down - it'd be the same cost to retrieve the details as any other list - need to get details for each item because tmdb doesn't give the info in the original call.

Service monitor is probably the better option when it's only for the focused item. I'll look at adding an override flag for the widget container prop in info dialog.

**Comment by jurialmunkey** [comment] 2020-03-22 21:42
Can you test latest version. You can now override the default service monitor behaviour in info dialog by setting this skin setting:
`Skin.SetBool(TMDbHelper.ForceWidgetContainer)`

You have two possible approaches. You can toggle it on and off as needed. OR you could just set it once and leave it on.

If you just leave it on, you will probably need to clear the widget container property onload of info dialog and then reset on exit:
```xml
<onload>SetProperty(TMDbTemp,$INFO[Window(Home).Property(TMDbHelper.WidgetContainer)],Home)</onload>
<onload>ClearProperty(TMDbHelper.WidgetContainer,Home)</onload>
<onunload>SetProperty(TMDbHelper.WidgetContainer,$INFO[Window(Home).Property(TMDbTemp)],Home)</onunload>
<onunload>ClearProperty(TMDbTemp,Home)</onunload>
```

**Comment by skyfsza** [comment] 2020-03-23 08:43
Thanks for adding this.

SM now updates with the WidgetContainer and I can get my Biography info inside VideoInfo.

One issue I seem to be having now is when you first open Video Info - before focusing one of the widgets inside VideoInfo and changing the WidgetContainer -  SM seems to clear all values of the parent VideoInfo item.  

Using your code above in DialogVideoInfo (minus the onload ClearProperty for WidgetContainer)
<onload>SetProperty(TMDbTemp,$INFO[Window(Home).Property(TMDbHelper.WidgetContainer)],Home)</onload>
<onunload>SetProperty(TMDbHelper.WidgetContainer,$INFO[Window(Home).Property(TMDbTemp)],Home)</onunload>
<onunload>ClearProperty(TMDbTemp,Home)</onunload>

Focused on home widget:
Window(Home).Property(TMDBHelper.ListItem.Label) The Trials of Gabriel Fernandez
Window(Home).Property(TMDbHelper.WidgetContainer) 43006

As VideoInfo opens:
Window(Home).Property(TMDBHelper.ListItem.Label) 
Window(Home).Property(TMDbHelper.WidgetContainer) 43006

**Comment by jurialmunkey** [comment] 2020-03-23 12:33
It's probably because the property is being cleared so it is triggering the service monitor again. 

You might need to just toggle the force setting as needed rather than doing the onload/unload method. (I didn't actually test the onload/unload way, so I wasn't sure if it would work properly or not).
