### ISSUE TITLE
New release not opening an addon  on TMDB helper on K 19.5

### ISSUE THREAD

**Issue by DJB628** [jurialmunkey/plugin.video.themoviedb.helper#966] opened 2022-12-30 12:19 UTC
### Describe the bug

It works fine before the latest update of Addon, but yesterday has stopped working. I've tested on other devices with the same issue, if I don't update the Addon, it works fine. Just bringing it to your attention. 

### Steps To Reproduce

One device I didn't update Fen and works fine, others have been updated and stopped working

### Debug log

If Fen is not updated to the latest release from Dec 29, it works fine.

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by tekker** [comment] 2022-12-30 12:51
@DJB628 This is due to a change made in the most recent version of FEN.

The TMDBPlayers.json file will need to be updated to reflect the changes made in the FEN source file:
```
plugin.video.fen/resources/lib/modules/router.py

lines 37-41

(v32)
elif '_play' in mode or 'play_' in mode:
		if mode == 'play_media':
			from modules.sources import Sources
			Sources().playback_prep(params)
		elif mode == 'media_play':
			

(v33)
elif 'playback.' in mode:
		if mode == 'playback.media':
			from modules.sources import Sources
			Sources().playback_prep(params)
		elif mode == 'playback.video':
```

If you are able to edit the JSON player resolver settings, changing the line in the FEN settings resolver by updating the player and modifying the JSON file on disk, ie (by setting resolver=true and clicking Save to create a customised JSON resolver for FEN Direct)

```
eterna:~/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players # cat direct.fen.select.json

{
    "name": "Fen Source Select",
    "plugin": "plugin.video.fen",
    "priority": 500,
    "play_movie": "plugin://plugin.video.fen/?mode=playback.media&media_type=movie&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}&autoplay=false",
    "play_episode": "plugin://plugin.video.fen/?mode=playback.media&media_type=episode&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}&autoplay=false",
    "is_resolvable": "true"
}
```

**Comment by DJB628** [comment] 2022-12-30 12:53
Thanks, above my pay grade, I was just posting to make it aware, no rush. Hopefully an update will be release when he has time

**Comment by AakashC2020** [comment] 2022-12-30 16:24
> @DJB628 This is due to a change made in the most recent version of FEN.
> 
> The TMDBPlayers.json file will need to be updated to reflect the updates made to the FEN source files:
> 
> FEN has changed the routing used for the player from:
> 
> `plugin://plugin.video.fen/?mode=play_media&media_type=`
> 
> TO:
> 
> `plugin://plugin.video.fen/?mode=playback.media&media_type=`
> 
> ```
> plugin.video.fen/resources/lib/modules/router.py
> 
> lines 37-41
> 
> (v32)
> elif '_play' in mode or 'play_' in mode:
> 		if mode == 'play_media':
> 			from modules.sources import Sources
> 			Sources().playback_prep(params)
> 		elif mode == 'media_play':
> 			
> 
> (v33)
> elif 'playback.' in mode:
> 		if mode == 'playback.media':
> 			from modules.sources import Sources
> 			Sources().playback_prep(params)
> 		elif mode == 'playback.video':
> ```
> 
> If you are able to edit the JSON player resolver settings, changing the line in the FEN settings resolver by updating the player and modifying the JSON file on disk, ie (by setting resolver=true and clicking Save to create a customised JSON resolver for FEN Direct)
> 
> ```
> eterna:~/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players # cat direct.fen.select.json
> 
> {
>     "name": "Fen Source Select",
>     "plugin": "plugin.video.fen",
>     "priority": 500,
>     "play_movie": "plugin://plugin.video.fen/?mode=playback.media&media_type=movie&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}&autoplay=false",
>     "play_episode": "plugin://plugin.video.fen/?mode=playback.media&media_type=episode&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}&autoplay=false",
>     "is_resolvable": "true"
> }
> ```

Hi @tekker,

Thanks a lot! I was facing the same issue and as per your instructions I've modified the code in the Fen JSON player and it works like a charm again! :)

Thanks and Regards,
ShibajiCh.

**Comment by xyzfre** [comment] 2022-12-30 17:30
> @DJB628 This is due to a change made in the most recent version of FEN.
> 
> 
> 
> The TMDBPlayers.json file will need to be updated to reflect the updates made to the FEN source files:
> 
> 
> 
> 
> 
> FEN has changed the routing used for the player from:
> 
> 
> 
> ``` plugin://plugin.video.fen/?mode=play_media&media_type= ```
> 
> 
> 
> TO:
> 
> 
> 
> ``` plugin://plugin.video.fen/?mode=playback.media&media_type= ```
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ```
> 
> plugin.video.fen/resources/lib/modules/router.py
> 
> 
> 
> lines 37-41
> 
> 
> 
> (v32)
> 
> elif '_play' in mode or 'play_' in mode:
> 
> 		if mode == 'play_media':
> 
> 			from modules.sources import Sources
> 
> 			Sources().playback_prep(params)
> 
> 		elif mode == 'media_play':
> 
> 			
> 
> 
> 
> (v33)
> 
> elif 'playback.' in mode:
> 
> 		if mode == 'playback.media':
> 
> 			from modules.sources import Sources
> 
> 			Sources().playback_prep(params)
> 
> 		elif mode == 'playback.video':
> 
> ```
> 
> 
> 
> If you are able to edit the JSON player resolver settings, changing the line in the FEN settings resolver by updating the player and modifying the JSON file on disk, ie (by setting resolver=true and clicking Save to create a customised JSON resolver for FEN Direct)
> 
> 
> 
> ```
> 
> eterna:~/.kodi/userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players # cat direct.fen.select.json
> 
> 
> 
> {
> 
>     "name": "Fen Source Select",
> 
>     "plugin": "plugin.video.fen",
> 
>     "priority": 500,
> 
>     "play_movie": "plugin://plugin.video.fen/?mode=playback.media&media_type=movie&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}&autoplay=false",
> 
>     "play_episode": "plugin://plugin.video.fen/?mode=playback.media&media_type=episode&query={showname}&year={year}&season={season}&episode={episode}&ep_name={title}&tmdb_id={tmdb}&premiered={firstaired}&autoplay=false",
> 
>     "is_resolvable": "true"
> 
> }
> 
> ```
> 
> 
> 
> 
> 
> 

Thank you @tekker GREAT JOB💯 got it working following your steps going to save this post

**Comment by Tikipeter** [comment] 2022-12-30 21:29
@DJB628 

Could you close this please out of respect to Jurial.

Player issues, especially pointing to addons like Fen, should NEVER be posted on this github.

Thanks.

**Comment by DJB628** [comment] 2022-12-30 23:24
I'm sorry, I take full responsibility for that, My Bad, I did edit my post but I'm not able to edit the other post. 


> @DJB628
> 
> Could you close this please out of respect to Jurial.
> 
> Player issues, especially pointing to addons like Fen, should NEVER be posted on this github.
> 
> Thanks.

**Comment by DJB628** [comment] 2022-12-30 23:25
I closed it out, cheers

**Closed as completed** 2022-12-30 23:24 UTC
Labels: bug

**Comment by jurialmunkey** [comment] 2022-12-31 00:31
> "plugin://plugin.video.fen/?mode=playback.media&media_type=movie&query={name}&year={year}&poster={poster}&title={title}&tmdb_id={id}&autoplay=false",


@tekker - not certain because I haven't looked at the code but I'd bet that the plugin expects url percent encoding for special characters in the plugin:// uri. 

In that case you should use the `_url` affix for the keys that support it in the URI
 https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#special-suffixes-for-plugin-uri

For instance, use `{name_url}` instead of `{name}` so that any special characters in the name are replaced with percent encoded characters so that they don't break the URI - - eg if a movie has an `&` character that's not percent encoded it's going to break because the plugin will think its a keyword separator

**Comment by tekker** [comment] 2022-12-31 03:09
@jurialmunkey Thanks jurial I'll test it out with ``name_url`` and see what happens

**Comment by jurialmunkey** [comment] 2022-12-31 06:05
@tekker - 

From a quick look at the code, the important value for playback is tmdb_id. As far as I gather, the query field is only used for subtitles. So a broken query field isn't going to affect playback but it will affect subtitles.

That plugin's `router.py` passes the paramstring through urllib.parse.parse_qsl which expects percent encoding. The unencoded `&` will be read as the start of a new name/value pair.

For example:

Input:

`dict(parse_qsl('mode=playback.media&media_type=episode&query=Law & Order: Special Victims Unit&year=1999&season=1&episode=1&ep_name=Payback&tmdb_id=2734&premiered=1999-09-20&autoplay=false', keep_blank_values=True))`

Output:

```
{
'mode': 'playback.media',
'media_type': 'episode',
'query': 'Law ',
' Order: Special Victims Unit': '',
'year': '1999',
'season': '1',
'episode': '1',
'ep_name': 'Payback',
'tmdb_id': '2734',
'premiered': '1999-09-20',
'autoplay': 'false'
}
```

^ See how the query key is only `Law ` and the rest is being interpreted as a new blank key in the dictionary.

It's still going to work for playback because the tmdb_id is intact but you'll get unexpected behaviour for other functions.

**Comment by DJB628** [comment] 2022-12-31 11:20
@jurialmunkey , I did take out all the references to the named addon in my post, but I was not able to removed it from other posters. So if you can, that would be great, don't want the addon Dev to be mad.

**Comment by xyzfre** [comment] 2022-12-31 11:27
No disrespect to anybody PLEASE but I do see a new commit in the json.openplayers hasn't been added yet ,,on GitHub my apologies again if I shouldn't be posting this
