### ISSUE TITLE
NextPage Feature broken inside AuraMod Information View

### ISSUE THREAD

**Issue by jojobrogess** [jurialmunkey/plugin.video.themoviedb.helper#676] opened 2022-03-07 11:01 UTC
Using latest AuraMod and ThemoviedbHelper, inside the information view.
I use real library files btw, so I'm not looking within tmdbhelper. This is the home view with Skin Helper/Skin supplied widgets. 
Happens in TV Shows, Movies, where ever I can get that button to appear.

Idk what the correct logic is, but I doubt it refreshes the content there on that screen(would be cool though), so I'm pretty sure the button should take you inside tmdbhelper to that secondary page for that specific list?  
Either way, it looks like it just selects the first _in_ the list rather than the next page _of_ the list. 

https://user-images.githubusercontent.com/17692472/157010152-714430af-fefb-4dbd-acaa-b1638864cd2f.mp4

 
********************************************************

There also seems to be a bug when you try to use the context menu on items inside that view:
You get a error notification, and if you continue on and select information, it takes you there but you loose focus. 
I would assume the focus part is the skins deal, but the notification of error might be something 

IF this is more for `context.themoviedb.helper`, please let me know and I'll post it over there 

Sound is applicable in this video, after I get the notification I press enter to select `information` and nothing happens.
(well actually the color changes slightly, giving the impression that something happened)
I have to press it again to active it. I'm pretty sure that's because of the notification popping up, taking focus? 

https://user-images.githubusercontent.com/17692472/157010795-b84dd624-2de1-43cb-9847-0ef677712b1a.mp4

[logs for this](https://paste.kodi.tv/qofewiziju.kodi)

The interesting parts:

```
2022-03-07 02:12:39.751 T:8444    DEBUG <general>: CTextureBundleXBT::CloseBundle - Closed bundle
2022-03-07 02:12:39.790 T:8444    DEBUG <general>: Infobool '!string.isempty(listitem.property(autocache))' still used by 3 instances
2022-03-07 02:12:39.790 T:8444    DEBUG <general>: Infobool '!string.isempty(listitem.property(autoid)) + [!string.isequal(listitem.property(autoaction),static) + !string.isequal(listitem.property(autoaction),merged)]' still used by 3 instances
2022-03-07 02:12:39.790 T:8444    DEBUG <general>: Infobool '!string.isempty(listitem.property(tmdbhelper.context.addlibrary))' still used by 3 instances
2022-03-07 02:12:39.790 T:8444    DEBUG <general>: Infobool '!string.isempty(listitem.property(tmdbhelper.context.artwork))' still used by 3 instances
2022-03-07 02:12:39.791 T:8444    DEBUG <general>: Infobool '!string.isempty(listitem.property(tmdbhelper.context.playusing))' still used by 3 instances
2022-03-07 02:12:39.791 T:8444    DEBUG <general>: Infobool '!string.isempty(listitem.property(tmdbhelper.context.refresh))' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '!string.isempty(listitem.property(tmdbhelper.context.related))' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '!string.isempty(listitem.property(tmdbhelper.context.sorting))' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '!string.isempty(listitem.property(tmdbhelper.context.trakt))' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '!string.isempty(window(home).property(currentskin)) + [string.isequal(listitem.dbtype,movie) | string.isequal(listitem.dbtype,set) | string.isequal(listitem.dbtype,tvshow) | string.isequal(listitem.dbtype,artist) | string.isequal(listitem.dbtype,album) | string.isequal(listitem.dbtype,musicvideo) | container.content(addons)] + !window.isvisible(home)' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '!string.isempty(window(home).property(currentskin)) + string.isequal(listitem.dbtype,set) + !window.isvisible(home)' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '!string.isempty(window(home).property(skinhelper.enableanimatedposters)) + container.content(movies)' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '!string.isempty(window(home).property(skinhelper.enablemusicart)) + 
                                                                       [container.content(albums) | container.content(artists) | container.content(songs)]' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '!string.isempty(window(home).property(skinhelper.enablepvrthumbs)) + 
                                                                       [window.isactive(mypvrchannels.xml) | 
                                                                       window.isactive(mypvrguide.xml) | window.isactive(mypvrrecordings.xml) | 
                                                                       window.isactive(mypvrtimers.xml) | window.isactive(mypvrsearch.xml)]' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '[string.isequal(listitem.dbtype,episode) | string.isequal(listitem.dbtype,movie)] + string.isempty(listitem.property(tmdbhelper.context.playusing)) + string.isempty(listitem.property(item.info))' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '[string.isequal(listitem.dbtype,episode) | string.isequal(listitem.dbtype,tvshow) | string.isequal(listitem.dbtype,movie)] + string.isempty(listitem.property(tmdbhelper.context.refresh)) + string.isempty(listitem.property(item.info))' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '[string.isequal(listitem.dbtype,episode) | string.isequal(listitem.dbtype,tvshow) | string.isequal(listitem.dbtype,movie)] + string.isempty(listitem.property(tmdbhelper.context.related)) + string.isempty(listitem.property(item.info))' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '[string.isequal(listitem.dbtype,episode) | string.isequal(listitem.dbtype,tvshow) | string.isequal(listitem.dbtype,movie)] + string.isempty(listitem.property(tmdbhelper.context.trakt)) + string.isempty(listitem.property(item.info))' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool '[string.isequal(listitem.dbtype,tvshow) | string.isequal(listitem.dbtype,movie)] + string.isempty(listitem.property(tmdbhelper.context.artwork)) + string.isempty(listitem.property(item.info))' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool 'container.content(addons)' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool 'container.content(albums)' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool 'container.content(artists)' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool 'container.content(movies)' still used by 3 instances
2022-03-07 02:12:39.793 T:8444    DEBUG <general>: Infobool 'container.content(songs)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'skin.hassetting(skin_enablepvrartwork)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.contains(listitem.folderpath, plugin://plugin.program.autowidget)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(autocache))' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(autoid))' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(item.info))' still used by 7 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(tmdbhelper.context.addlibrary))' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(tmdbhelper.context.artwork))' still used by 4 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(tmdbhelper.context.playusing))' still used by 4 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(tmdbhelper.context.refresh))' still used by 4 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(tmdbhelper.context.related))' still used by 4 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(tmdbhelper.context.sorting))' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(listitem.property(tmdbhelper.context.trakt))' still used by 4 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(window(home).property(currentskin))' still used by 4 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(window(home).property(skinhelper.enableanimatedposters))' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(window(home).property(skinhelper.enablemusicart))' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isempty(window(home).property(skinhelper.enablepvrthumbs))' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.dbtype,album)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.dbtype,artist)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.dbtype,episode)' still used by 7 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.dbtype,movie)' still used by 9 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.dbtype,movie) | string.isequal(listitem.dbtype,tvshow) | string.isequal(listitem.dbtype,season) | string.isequal(listitem.dbtype,episode)' still used by 4 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.dbtype,musicvideo)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.dbtype,season)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.dbtype,set)' still used by 4 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.dbtype,tvshow)' still used by 8 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.property(autoaction),merged)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(listitem.property(autoaction),static)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'string.isequal(window(10000).property(context.autowidget),true)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'system.hasaddon(script.module.pvr.artwork)' still used by 3 instances
2022-03-07 02:12:39.794 T:8444    DEBUG <general>: Infobool 'system.hasaddon(script.module.pvr.artwork) + skin.hassetting(skin_enablepvrartwork) + [window.isactive(mypvrchannels.xml) | window.isactive(mypvrguide.xml) | window.isactive(mypvrrecordings.xml) | window.isactive(mypvrtimers.xml) | window.isactive(mypvrsearch.xml)]' still used by 3 instances
2022-03-07 02:12:39.795 T:8444    DEBUG <general>: Infobool 'window.isactive(mypvrchannels.xml)' still used by 4 instances
2022-03-07 02:12:39.795 T:8444    DEBUG <general>: Infobool 'window.isactive(mypvrguide.xml)' still used by 4 instances
2022-03-07 02:12:39.795 T:8444    DEBUG <general>: Infobool 'window.isactive(mypvrrecordings.xml)' still used by 4 instances
2022-03-07 02:12:39.795 T:8444    DEBUG <general>: Infobool 'window.isactive(mypvrsearch.xml)' still used by 4 instances
2022-03-07 02:12:39.795 T:8444    DEBUG <general>: Infobool 'window.isactive(mypvrtimers.xml)' still used by 4 instances
2022-03-07 02:12:39.795 T:8444    DEBUG <general>: Infobool 'window.isvisible(home)' still used by 4 instances
2022-03-07 02:12:39.795 T:8444     INFO <general>: Unloaded skin

```
```
2022-03-07 02:12:31.498 T:9860    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: list_tmdb() missing 1 required positional argument: 'tmdb_type'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Joe\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 8, in <module>
                                                       Container().router()
                                                     File "C:\Users\Joe\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container\router.py", line 477, in router
                                                       self.get_directory()
                                                     File "C:\Users\Joe\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container\router.py", line 439, in get_directory
                                                       items = self.get_items(**self.params)
                                                     File "C:\Users\Joe\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container\router.py", line 410, in get_items
                                                       return self._get_items(route[info]['route'], **kwargs)
                                                     File "C:\Users\Joe\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\container\router.py", line 381, in _get_items
                                                       return func['lambda'](getattr(self, func['getattr']), **kwargs)
                                                     File "C:\Users\Joe\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\addon\constants.py", line 156, in <lambda>
                                                       'lambda': lambda func, **kwargs: func(**kwargs),
                                                   TypeError: list_tmdb() missing 1 required positional argument: 'tmdb_type'
                                                   -->End of Python script error report<--
                                                   
2022-03-07 02:12:31.498 T:9860    DEBUG <general>: CPythonInvoker::onExecutionDone(41, C:\Users\Joe\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py)
2022-03-07 02:12:31.537 T:8444    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
```

**Comment by drinfernoo** [comment] 2022-03-07 13:46
That's an AuraMOD issue 🤔

**Comment by jurialmunkey** [comment] 2022-03-07 15:19
Yep, these are all skin issues.

The TMDbHelper error on context menu is likely due to AuraMod relying on a $VAR skin variable nested inside another skin variable to set tmdb_type=. The problem is that when a modal dialog pops-up (like context menu for example) then Kodi will only evaluate the parent variable, so any nested child variable becomes blank (hence the error because tmdbhelper needs a type of content to call that particular list). The child variable being blank on a modal dialog is a long standing Kodi bug that hasn't been fixed, so skins needs to work around it by not nesting important variables. 

The next page issue is due to the skin overriding onclick behaviour and not properly closing the info dialog when a folder is clicked (e.g. next page). Alternatively, the skin _could_ specify nextpage=false to hide the next page folder. Either way, the skin needs to manage it.

**Closed as completed** 2022-03-07 15:20 UTC
Labels: skin-issue

**Comment by jojobrogess** [comment] 2022-03-07 20:11
Ahh cool, thank you for the quick reply!

**Comment by inb4after** [comment] 2022-06-24 21:20
@jurialmunkey Could TMDBHelper handle the list for us, so when we press the next page button, the list content updates in real time to the next page without us needing to close the dialog and open TMDBHelper addon?

Then if previous page and next page buttons are available on pages 2 and above, we can navigate as many pages as we want, without leaving the info page of the original item?

**Comment by jurialmunkey** [comment] 2022-06-25 00:15
@inb4after Not possible from the plugin side. Kodi controls when containers reload not the plugin. Next page is just a subfolder that opens a new path (think of each page as a season inside a season like nested dolls - it isn't flat). 

You could fake it in the skin by using a window property for the page= value in the container path. Then use static items faking next/prev items on ends that update the page window property appropriately. 

Since that will change the path it will force kodi to reload the container. And since it changes the page number, the plugin will then be supplying the new page of items.

**Comment by inb4after** [comment] 2022-06-25 03:03
> @inb4after Not possible from the plugin side. Kodi controls when containers reload not the plugin. Next page is just a subfolder that opens a new path (think of each page as a season inside a season like nested dolls - it isn't flat).
> 
> You could fake it in the skin by using a window property for the page= value in the container path. Then use static items faking next/prev items on ends that update the page window property appropriately.
> 
> Since that will change the path it will force kodi to reload the container. And since it changes the page number, the plugin will then be supplying the new page of items.

This workaround seems to be working so far, however I'm not sure how to implement increasing/decreasing the window property and using it as a dynamic/true counter instead of a static counter with a limited number of pages.

**Comment by jurialmunkey** [comment] 2022-06-25 03:40
You would need to write a script to do the math as there's no addition/increment functions in the skinning engine.

If youre clever with includes you can easily make 100 hardcoded includes in 20 lines of skincode by using params to separate the ones and tens digits. Then you only need 1 line per 10 includes (ie make a "tens" includes block of positions 0-9 and then a increment the tens position of those using a param)

**Comment by inb4after** [comment] 2022-06-25 14:15
> You would need to write a script to do the math as there's no addition/increment functions in the skinning engine.
> 
> If youre clever with includes you can easily make 100 hardcoded includes in 20 lines of skincode by using params to separate the ones and tens digits. Then you only need 1 line per 10 includes (ie make a "tens" includes block of positions 0-9 and then a increment the tens position of those using a param)

I went with the first option using a script so we can access unlimited pages and I can now navigate back and forth using the static items.

However, when the window property paging is set to page 3 and beyond, the list appears to be empty.

The first two pages are populated with items, however it seems to be a hard limit within TMDBHelper.

**Comment by jurialmunkey** [comment] 2022-06-25 14:55
There's no page limit in tmdbhelper. There's no difference between viewing page 3 in myvideonav or in a container on home. It sounds like you have a misconfigured path.

**Comment by inb4after** [comment] 2022-06-25 16:14
> There's no page limit in tmdbhelper. There's no difference between viewing page 3 in myvideonav or in a container on home. It sounds like you have a misconfigured path.

I was trying out the original solution earlier: closing the dialog and removing the skin `<onclick>` overrides for the list so TMDBHelper's next page item would open the addon (page 2 of `info=recommendations`). When that list opened in `MyVideoNav` there was no next page button to access page 3.

As an example (I removed all nested variables and tested the paths directly):

Filled list: `plugin://plugin.video.themoviedb.helper/?info=recommendations&amp;type=movie&amp;query=f9&amp;page=2&amp;nextpage=false`

Empty list: `plugin://plugin.video.themoviedb.helper/?info=recommendations&amp;type=movie&amp;query=f9&amp;page=3&amp;nextpage=false`

**Comment by jurialmunkey** [comment] 2022-06-25 17:13
That's because there are only 40 recommended movies on TMDb for F9. There's only two pages worth of items available.

Recommendations, by nature, are limited. If they went on forever they wouldn't be recommendations. Just like there's only going to be X movies by a director/writer/studio or X cast members etc.

There's no hard limit on pages in TMDbHelper but it can't display more items than are available on the server.

`movie/385128/recommendations`

[Output of API call](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/8985235/tmdb_movie385128recommendations.txt) 

```json
"response": {
  "page": 1,
  "results": [...],
  "total_pages": 2,
  "total_results": 40
}
```

**Comment by inb4after** [comment] 2022-06-25 17:48
I see, that makes sense, it must be a hard limit on TMDB or their API. 

Could you check if other popular movies such as The Dark Knight also has 2 pages/40 items only? I've not found any content with 3 pages available.

I will probably just add `nextpage=false` for these lists without supporting further pages.

EDIT: I've just tested `info=similar` and this list has many more pages. It must be an intentional TMDB server limit as you mentioned. I'll continue working on the multi-page support which may be still useful for some lists.

**Comment by jurialmunkey** [comment] 2022-06-26 00:54
Fairly sure all recommendations are limited to 40.TMDb uses an algorythm to calculate these based upon user rating history and favourites (ie users who like X also like Y) so there needs to be a limit otherwise they start getting irrelevant fairly quickly.

Similar is mapped using genre+keywords so goes much further as it is less specific.

FYI You can log any api call using the function in expert settings. It outputs to a file in TMDbH addon_data folder. You just need the movie id from the website for recommendations

It's as simple as inputting 
movie/385128/recommendations
Into the popup keyboard

**Comment by inb4after** [comment] 2022-08-16 06:39
@jurialmunkey

For static next/previous page items inside a single fixed list container, is there a workaround/hack to be able to use `onfocus` and `onunfocus` for these items only?

For example:

```xml
<content>
    <item>
        <onfocus>action</onfocus>
        <onunfocus>action</onunfocus>
        <label>text</label>
        <icon>iconpath</icon>
        <visible>condition</visible>
    </item>
</content>
```

The above does not work as intended, I assume because it's not supported yet.

**Comment by jurialmunkey** [comment] 2022-08-16 08:19
@inb4after not possible to specify an onfocus/onunfocus for an item directly but you can hack it by adding a hidden button control to the focusedlayout of the list. The hidden button will trigger its onfocus on every item change, so you can then use a condition in that based on a property of the item

**Comment by inb4after** [comment] 2022-08-17 07:47
> @inb4after not possible to specify an onfocus/onunfocus for an item directly but you can hack it by adding a hidden button control to the focusedlayout of the list. The hidden button will trigger its onfocus on every item change, so you can then use a condition in that based on a property of the item

Thanks again for the advice, it works as intended, just had to add a skin setting check as the hidden button changes a bool skin setting. It should avoid the problem below. 

I was testing earlier with a different idea and made a mistake with setting that skin setting twice at the same time. This resulted in the skin setting getting stuck in the `true` position.

`Skin.Reset` had no effect on it. `Skin.ToggleSetting` worked, but as soon as I needed to `Skin.SetBool` for something, it would end up stuck again. 

The only fix was to remove two entries of that skin setting from the skin `settings.xml`. It looked like one entry was the correct bool type, but a second entry had appeared and was a string type with an empty value.

**Comment by jurialmunkey** [comment] 2022-08-17 08:49
Depending on what you're doing, you might be better off with using a window property rather than a skin setting. I'd only use a skin setting if you need to keep the value after closing Kodi. Window properties are generally faster and you don't need to worry about disk writes etc.

You can mimic a bool setting with a property by checking `!String.IsEmpty(Window(Home).Property(MyProp))`
Toggle it off and on by doing `ClearProperty(MyProp,Home)` and `SetProperty(MyProp,1,Home)` respectively
