### ISSUE TITLE
[Feature Request] Add the option to play show's season and also play the entire show

### ISSUE THREAD

**Issue by movianlost** [jurialmunkey/plugin.video.themoviedb.helper#527] opened 2021-07-06 14:14 UTC
I want to be able to bring the context menu on a show or on a season and click on play which will send the request to play the whole show or the whole season respectively.

Part of this feature is available on Elementum, I can bring a context menu on a season and click on play and it will search for the entire season and not just a single episode. 

This feature is important because most shows are not packaged into episodes but rather,  into whole show package or by seasons.

I currently use Elementum for browsing content and as the player of the content, I would prefer to start using themoviedbHelper because it is more complete, but the lack of show/season search is a problem.

**Comment by jurialmunkey** [comment] 2021-07-07 00:39
Duplicate of this request: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/312

It is something I was working on but I met some roadblocks with some player types which prevented my finishing it. I will look into it again soon. Closing this issue to keep things in one thread.

**Closed as completed by jurialmunkey** 2021-07-07 00:39 UTC
