### ISSUE TITLE
Next up episodes 

### ISSUE THREAD

**Issue by 7E1EVEN** [jurialmunkey/plugin.video.themoviedb.helper#38] opened 2019-12-28 10:49 UTC
I would love for TMDbHelper to have a next up episode playlist instead of next up TV Shows.
That way, if you create a widget for it. It’ll be just one click to start watching.

Thank you

**Comment by jurialmunkey** [comment] 2019-12-28 22:36
Can you test latest commit? I've added a new section under Tvshows called "Your Next Episodes" which links directly to the episodes.

**Comment by SoulTV** [comment] 2019-12-28 23:28
@jurialmunkey please don't remove the next up tv shows widget tho

**Comment by jurialmunkey** [comment] 2019-12-29 00:15
@SoulTV - Never! I use that one all the time 😉 This episode one is in addition to the TvShows one.

I find the Tvshows one more useful personally because it allows you to skip ahead to a later episode, which is particularly useful if I watch an episode at a mate's place and haven't yet updated my Trakt history to reflect that.

**Comment by 7E1EVEN** [comment] 2019-12-29 01:10
Thank you very much. 

But I’m not able to check it out right now. I’m away from home. But as soon as I get back I’ll let you know.

**Comment by jurialmunkey** [comment] 2019-12-29 01:31
I'm pretty sure it is working correctly from my tests but confirmation when you get the chance would be good!

**Comment by 7E1EVEN** [comment] 2019-12-29 19:14
Awesome, I can locate it. I can also set it up as a widget but when I try to play a show, either local or stream, I get this error:

> 2019-12-29 19:59:33.833 T:4067536896   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.themoviedb.helper/?info=play&widget=True&episode=11&tmdb_id=1958025&season=4&type=tv]

> 2019-12-29 19:59:36.207 T:3032466144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'is_local' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 10, in <module>
                                                TMDbScript.router()
                                              File "/home/osmc/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script.py", line 180, in router
                                                self.play()
                                              File "/home/osmc/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script.py", line 65, in play
                                                season=self.params.get('season'), episode=self.params.get('episode'))
                                              File "/home/osmc/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/player.py", line 113, in play
                                                if is_local:
                                            UnboundLocalError: local variable 'is_local' referenced before assignment
                                            -->End of Python script error report<--

Also, I have 2 shows that don't show epsiode names. Only the episode numbers.

Thank you.

**Comment by jurialmunkey** [comment] 2019-12-29 22:46
@7E1EVEN - Okay, I think this issue should be fixed now. Can you test and confirm?

>
> Also, I have 2 shows that don't show epsiode names. Only the episode numbers.

What shows don't have episode names? And what season / episode? 
It most likely means that TMDb doesn't have details for those episodes yet but I'll look into it to make sure.

**Comment by 7E1EVEN** [comment] 2019-12-30 00:02
It doesn’t do anything now. It just loses focus then comes back. No logs either. 

The shows in question are:
My Hero Academia - S04E11 - Lemillion
Black-ish - S06E08 - O, Mother Where Art Thou?

**Comment by jurialmunkey** [comment] 2019-12-30 02:11
@7E1EVEN - Hmmm, strange. It's working for me.

Can you download latest version and turn on the addon's debug logging by going to `Video Addons > TMDbHelper > Info > Settings > Expert > Debug Logging (Enable) > OK`

Then try to play an item from nextepisodes list and post full debug log here using a log paste website like pastebin: https://pastebin.com/

I don't care if you have banned add-ons as they won't affect this issue - I just want to get to the bottom of the matter of why it's not playing.

**Comment by 7E1EVEN** [comment] 2019-12-30 11:01
After rebooting I can play files using Seren as a default player. But local files are skipped.
This doesn't happen with movies.

[Here is the debug log](https://pastebin.com/CsS6NCzX)

**Comment by jurialmunkey** [comment] 2019-12-30 11:42
What item is local that you are trying to play in that log? I only see you playing files with an external addon.

**Comment by 7E1EVEN** [comment] 2019-12-30 11:52
Yeah, exactly it doesn't even try to search locally first. It goes straight to external whereas with movies it works exactly as intented.

I have the first item in my library (My Hero Academia).

**Comment by jurialmunkey** [comment] 2019-12-30 21:35
The plugin *always* searches locally first. It only goes to an external player if it can't find a match in the local library. Most likely the TV Show Title returned by TMDb doesn't match the TV Show Title in your library.

As this wasn't the original reported issue, I wasn't logging any of the Kodi DB checks. I've now added some additional debugging for the local lookups.

Can you install new version and get me a fresh debug log so that I can confirm that it is failing to match the title and not some other issue. Also, what is the *exact* tvshowtitle of My Hero Academia listed as in your Kodi Library? Is it the English name or the Japanese one?

**Comment by 7E1EVEN** [comment] 2019-12-30 23:55
[Debug log](https://pastebin.com/bQnBi7vN)

I don't know if it matters but Trakt is having issues now, so streaming isn't working right at the moment.
It failed to play an item.

It's listed as ''My Hero Academia'', the english version.

**Comment by jurialmunkey** [comment] 2019-12-31 04:03
> 
> 
> [Debug log](https://pastebin.com/bQnBi7vN)
> 
> I don't know if it matters but Trakt is having issues now, so streaming isn't working right at the moment.
> It failed to play an item.
> 
> It's listed as ''My Hero Academia'', the english version.

I think you forgot to turn on the TMDbHelper's debug logging for that one...

I have noticed that Trakt is having some 502 connection errors at the moment. It shouldn't matter for playing local files though, as I use TMDb info to match with DBID.

For external players, Trakt supplies: `{trakt} {imdb} {tvdb} {slug} {epid} {epimdb} {eptmdb} {eptrakt}`. So if the Trakt look-up failed, then those infos will be empty when passed to external player.

**Comment by 7E1EVEN** [comment] 2019-12-31 04:33
You're right. I goofed. Here is the [new log](https://pastebin.com/MaiwNX2H)

**Comment by jurialmunkey** [comment] 2019-12-31 05:35
> 
> 
> You're right. I goofed. Here is the [new log](https://pastebin.com/MaiwNX2H)

Thanks!

Looking at the log, the title "My Hero Academia" is being found in the local library but it fails to match. The only thing that makes sense is that there is mismatch between the year in the library and what TMDb reports.

Can you download latest version and enable fuzzy matching for tvshows in the addon settings:
`Video Addons > TMDb Helper > Info > Settings > Players > Allow fuzzy matches for tvshows`

If this doesn't work then I'm completely stumped 😕

**Comment by 7E1EVEN** [comment] 2019-12-31 05:54
It worked! Thanks a lot!

You really went the extra mile. Your hard work is appreciated. 

Could you point me to the direction where I can donate? I don’t have much but you really deserve it. 

Again, thanks a lot and I hope you have a happy and safe new year!

**Comment by jurialmunkey** [comment] 2019-12-31 06:07
Excellent! Glad we got there in the end! 😁 

Paypal: http://www.paypal.me/jurialmunkey

**Closed by jurialmunkey** 2019-12-31 06:07 UTC

**Comment by drinfernoo** [comment] 2019-12-31 09:54
I'll get this one up on the repo tomorrow 👍
