### ISSUE TITLE
[BUG] Movie not being marked as watched 

### ISSUE THREAD

**Issue by vella9** [jurialmunkey/plugin.video.themoviedb.helper#1069] opened 2023-06-29 21:19 UTC
### Describe the bug

I saw a movie after the latest update to 5.1.20 and it did not mark as watched with the check mark. I manually marked the movie as watched via the Trakt options context menu but still the check mark did not appear.

### Steps To Reproduce

watch a movie
indicator not changing to check mark

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment] 2023-06-30 06:32
TMDbHelper does not scrobble watched status. That is up to whatever you use to watch the item.

However, the context Trakt option should work (and works for me). I'd need a debug log to have any chance of knowing what the issue is.

**Comment by vella9** [comment] 2023-06-30 08:02
I just noticed that this is occurring to 'in progress' items only. For some reason, the check mark is not being shown and the item stays in the 'in progress' widget. I had to manually remove the item from 'Remove from progress' under the Trakt options context menu.

When the item is searched for, it is being displayed correctly though with the check mark and all.

**Comment by jurialmunkey** [comment] 2023-07-01 01:43
Marking as watched does not necessarily remove progress. Items that have been watched can also be in-progress because Trakt stores and syncs watched history and progress status separately.

Updating watched status only changes information in watched history - it does not change progress status. Additionally, a change to Trakt's watched history sync list will not cause the progress sync list to have its cache refreshed on the server (and vice versa).

If the checkmark is displaying in search, then watched status is updating correctly. Progress is entirely separate from that status. If you want to remove progress information from an item then you must remove the progress.

**Closed as completed by jurialmunkey** 2023-07-01 01:43 UTC
Labels: bug
