### ISSUE TITLE
[BUG] Exit from info dialog, missing info

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/plugin.video.themoviedb.helper#826] opened 2022-08-22 10:06 UTC
### Describe the bug

When entered in tmdb helper, and then open info dialog, posters and almost all the information disappear when exiting.

### Steps To Reproduce

1. open tmdb helper
2. open context menu of some movie
3. select information
4. exit from info dialog

### Debug log

```
2022-08-22 11:52:43.804 T:14164   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: get_items() missing 1 required positional argument: 'tmdb_type'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\plugin.py", line 7, in <module>
                                                       Router(int(sys.argv[1]), sys.argv[2][1:]).run()
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\items\router.py", line 46, in run
                                                       self.get_directory()
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\items\router.py", line 39, in get_directory
                                                       container.get_directory()
                                                     File "C:\Users\Marko\AppData\Roaming\Kodi\addons\plugin.video.themoviedb.helper\resources\lib\items\container.py", line 239, in get_directory
                                                       items = self.get_items(**self.params)
                                                   TypeError: get_items() missing 1 required positional argument: 'tmdb_type'
                                                   -->End of Python script error report<--
```

### Screenshots and Additional Info

![bug](https://user-images.githubusercontent.com/74268331/185895347-a759ca15-e63b-4ca2-ab36-cd8aaa12c42e.png)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment] 2022-08-22 11:03
I cant reproduce this issue.

Also full log please. Snippets aren't useful because I can't see the surrounding context of what is occurring to cause the error.

**Comment by jurialmunkey** [comment] 2022-08-22 11:04
Also please try disabling trakt progress indicators. On some systems they cause problems with missing metadata

**Comment by matke-84** [comment] 2022-08-22 11:20
Yes, get resume points is a real problem. It's a real shame that this option causes so many problems with missing metadata. I thought a little about this issue. If it is somehow possible, that when we turn on this option, to create an additional option that would sync with Trakt with a small delay, I don't know what the minimum should be. Maybe it would be a better situation. You wouldn't get the information immediately after stopping watching the movie, but maybe there wouldn't be these problems. The same thing happens with the meta data in the osd menu. And it's a really good option and it would be a shame not to use it.

**Comment by xyzfre** [comment] 2022-08-22 14:00
I've been playing around with  the Trakt settings never realize disabling mostly all of them it's a major difference on start up

**Comment by xyzfre** [comment] 2022-08-22 14:02
![image](https://user-images.githubusercontent.com/49699869/185939707-a9fcb08a-7302-4371-826c-4343d502f3b2.jpeg) only left this one enable to experiment and Kodi start up went from 20 seconds To 6 seconds

**Comment by jurialmunkey** [comment] 2022-10-13 02:44
No workable solution for progress indicators currently. Needs to be fixed in Kodi, which will require making a test case to report the bug.

**Closed as not planned by jurialmunkey** 2022-10-13 02:44 UTC
Labels: bug
