### ISSUE TITLE
Sort order of TV Shows Watchlist is wrong. 

### ISSUE THREAD

**Issue by DaisyF8** [jurialmunkey/plugin.video.themoviedb.helper#119] opened 2020-03-01 17:21 UTC
(Movie Watchlist order is correct btw)

I'm using TV Shows Watchlist in list or widget, default sort order, 10 results.

I was removing and adding new and allready present shows a couple of times. When compared to the Trakt-website the order in TmdbHelper is :
2 4 5 6 8 9 10 1 3 7

The out of order placement isn't always consistent. The first Trakt show is never displayed first in TmdbHelper though. Mostly in 7th or 8th position.

To be complete, in all of the above my Trakt Watchlist on the Trakt website is sorted by "Recently added". And to get an easier overview I use filter "Movies" or "Shows". 

(Also, if a movie or episode is both in "Watchlist" AND "Collected"  in Trakt, it will (I think) get displayed at the top of the TmdbHelper list.)

**Comment by drinfernoo** [comment] 2020-03-01 18:11
Duplicate of #118?

**Closed** 2020-03-01 21:42 UTC

**Comment by DaisyF8** [comment] 2020-03-01 21:44
No, is separate I think. This occurs with 10 results.
