### ISSUE TITLE
Widget refresh speed

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#832] opened 2022-08-26 19:11 UTC
### Skin section

Home Widgets

### Current Behavior

Hi Jurialmunkey. Not a bug or feature request, more a general observation. 

Recently purchased an Odroid N2+ running Coreelec and created a widget setup on AH2 that provided a good performance to content balance…seven widgets in total that took 6-8 seconds to refresh after watching something. As a regular live tv user, the less time spent refreshing widgets after stopping a channel, the better, allowing me to stream other content without too much waiting (as Kodi’s internet/ mac address is busy while widgets refresh). 

Over the last few weeks I’ve noticed the Odroid has been taking around 12-14 seconds for all widgets to refresh, whereas my windows laptop continues to fly through this process at the same speed it always has. 

Nothing has changed in my setup/ network  so wonder if the Odroid’s flavour of Linux hasn’t adapted well to some changes made to AH2/ tmdb helper recently?  

Not expecting a solution to the issue but hopefully it’s useful feedback. Thanks. 

### Expected Behavior

.

### Steps To Reproduce

.         

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment] 2022-08-27 00:58
Nothing in the skin is going to impact the loading speed really unless you switched to flixart appearance preset because that's a massive performance hit. Blur is slow and flixart is even worse because it does a lot of image transformation (flip, tile, and diffuse) and has more render layers. 

If these are all tmdbhelper widgets, there have been some changes on the disk caching front but I'm surprised it has had a performance hit - as every test I've done it has been faster not slower. If this is a tmdbhelper related thing then I can transfer this issue over there. Would need a debug log for that (with the directory logging enabled in TMDbH expert settings) 

It's also very possible you simple had a slow connection at one point.

**Comment by ghost** [comment] 2022-08-27 02:01
Thanks for the response. Meant to say…this started happening before flixart was released - all widgets are tmdb helper widgets. 

Yeah sorry, should’ve probably posted this on tmdb helper page. If you could transfer the issue over I’ll send a debug log when I get a chance. Will also try a clean install first to rule out any other issues. Thanks.

**Comment by jurialmunkey** [comment] 2022-08-27 02:52
@Tee77 - No worries. Transferred over to TMDbH github.

Yes please, debug log with the directory timer reports setting enabled in TMDbH expert settings will help me see what part is causing the loading delay and if it is just API calls or an issue with caching. 

Also, do you know roughly what version of TMDbH you noticed this happening? 4.10.38 was when I changed mem and disk caching (roughly 3-4 days ago).  The change sped things up considerably on my NUC running windows but maybe not great on oDroid depending on your disk storage situation

I'm just looking at the oDroid specs. I see it has eMMC, microSD, and USB for disk storage options. What is your Kodi install userdata located on (specifically TMDbH's addon_data folder)? Because if it is microSD or USB the I/O speeds aren't going to be great which would explain the changes making performance worse for you.

**Comment by ghost** [comment] 2022-08-27 09:06
Thanks man.

> debug log with the directory timer reports setting enabled

Once enabled, should I reboot, reproduce widgets reloading after playing content, then click log output of TMDB request? Will this produce a log url I can share with you? Or should I generate a general kodi debug log?

> do you know roughly what version of TMDbH you noticed this happening

Sorry I can't remember. It feels as though it could've been around that time.

I have Kodi installed on eMMC on the Odroid - not using any other storage options.. I'm going to struggle to find time to do this over the weekend (family visiting) but want to do this properly, so will look to do a clean install and test, starting with an older version of tmdb helper and take a log each time (once I know how).

Appreciate your time.

**Comment by jurialmunkey** [comment] 2022-08-27 10:47
> Once enabled, should I reboot, reproduce widgets reloading after playing content, then click log output of TMDB request? Will this produce a log url I can share with you? Or should I generate a general kodi debug log?

Just a normal kodi log.

Enable the directory timer report setting in TMDbH expert settings and then get your widgets to refresh. 

The option gets TMDbH to output a timer report to the log each time it loads a container of items. It's really useful because it shows how long each stage of loading took, so really useful to determine whereabouts the slow down is or if it is just a server being slow etc.

> I have Kodi installed on eMMC on the Odroid - not using any other storage options

Hmmm eMMC should be plenty fast enough. Obviously not as fast as SSD but it's only text being read. It's not like we're reading massive amounts of data. Could be something linux specific with sqlite3 database caching.

> I'm going to struggle to find time to do this over the weekend (family visiting) but want to do this properly, so will look to do a clean install and test, starting with an older version of tmdb helper and take a log each time (once I know how).

No rush! Whenever you get the chance.

If you are going to go back to an older version, I'd recommend going to v4.10.38 as that was right before I change the caching so it will give a good indication if that was the issue.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.10.38

The other main change was when I moved a few functions out to their own module (the script.module.tmdbhelper one). I doubt it is the cause but if you don't see the performance return using v4.10.38 then that would be my next guess. That was v4.10.34 -- I wouldn't bother going back further than that.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.10.34

You might get AH2 complaining about dependencies when downgrading but you can get around that by changing the TMDbH dependency version in AH2's addon.xml
https://github.com/jurialmunkey/skin.arctic.horizon.2/blob/main/addon.xml#L7

Going back to 4.10.34 won't break anything in AH2 - there was just a small feature with some additional award info being added to the info dialog and upping the dependency is the only way I can get it to force TMDbH to update on Matrix

**Comment by ghost** [comment] 2022-08-28 13:52
Did a fresh install and enabled directory timer report settings - totally agree, that’s a really useful tool! 

TMDbH v4.10.34 http://ix.io/48SL

TMDbH v4.10.38 http://ix.io/48SR

TMDbH v4.11.2 http://ix.io/48SX

I’m not seeing the widget refresh speed that I was getting previously across any version, but to be honest, it’s good enough, and certainly not worth pursuing unless you find something obvious. The few extra seconds to refresh widgets just really stood to me as this process was so consistently snappy previously (tested regularly over a week or so with exact same widget/ kodi setup).

Anyway, thanks so much for taking a look at this. 

Cheers.

**Comment by jurialmunkey** [comment] 2022-08-28 15:00
Thanks. Ok so at least we can rule at the changes to the caching in 4.10.39 in that case, which is great because I didn't want to revert that if it could be avoided.

I think this might actually be a slow connection to Trakt. The fact that the sync and make stages of add_items are taking a big piece of time whereas the other parts aren't indicates an issue with a Trakt connection, as that's the main time hog in those stages.

For instance see this list - 
```
info=trakt_trending&tmdb_type=movie&widget=true&reload=
------------------------------
get_list       :   0.028 sec
add_items      :   5.796 sec
--build        :   0.317 sec
 - item_api    :   0.208 sec avg |   0.304 sec max |  19
 - item_ftv    :   0.118 sec avg |   0.234 sec max |  15
--sync         :   1.379 sec
--make         :   4.097 sec
------------------------------
Total          :   5.830 sec
```

- **get_list** 
How long it took to get the base list (the raw list of IDs). The list above was clearly cached hence the speed. The speed also indicates that our cache is working well (barely any time out of the total)
- **add_items**
The total time it took to retrieve the details the items in the list and add them to the directory. It is further broken down into components. Over 5 seconds here is a long time, especially since many of the item details were already cached.
  - **build**
  How long it took to retrieve the item details (either cached or online) and then map the metadata. It is broken down into item details (item_api = TMDb) and artwork (item_ftv = FanartTV). These are threaded which is why 19x item_api at 0.208s average per lookup and 15x item_ftv at 0.118s average per lookup only totals 0.317s. Barely anytime here, which indicates likely already cached.
  - **sync**
  When the widget is first called, TMDbH starts looking up Trakt watched history sync in a separate thread. After all the item details are added in the build section, it then needs to wait here for the sync to complete (so we can then add watched status). So this is the *remainder* of time it took in addition to it running the entire time the other sections were also going.
  - **make**
  This is the all the left over configuration of the item like adding watched status and progress. Pretty much only see a long period of time here if "Get resume points" is enabled and Trakt is slow on returning it.

I'll have a closer look at the logs to see if I can see anything unusual but based on the above and similar patterns on the other timer reports I'd almost certainly say this is an issue with Trakt connection. In particular, I'd recommend disabling "Get resume points" under Accounts in TMDbH settings and see if that helps

**Comment by ghost** [comment] 2022-08-29 10:59
Thanks for the detailed explanation.

I'm following up with two additional logs having turned off trakt watched indicators and episode counts/ set unwatched episode count/ resume points in tmdb helper settings. Rebooted and retested...

It looks like get_list is now taking the most time out of anything, except for the two trending movies/tv lists which are directly from tmdb helper's default trakt lists and seem to be flying now.

http://ix.io/490X

Except for ‘your next episodes’, the other trakt lists are created from my own mdblists (accessed via 'your lists' in tmdb helper's trakt section). Out of curiosity, I capped these lists to 20 items (via mdblist) to see if it had any effect on speed. Once these trakt lists had updated, I rebooted and tested again. 

http://ix.io/491f

If this kind of performance is not out of the ordinary, then let's just leave it here. Widget refresh speed seems decent enough. Thanks.

**Comment by jurialmunkey** [comment] 2022-08-29 12:48
> It looks like get_list is now taking the most time out of anything, except for the two trending movies/tv lists which are directly from tmdb helper's default trakt lists and seem to be flying now.

The difference here will be because when you enter the first page of a custom list that you own then the cache for it is refreshed in case you have added new items. By contrast, the default lists and custom lists by other users are cached for 24hrs since we can be relatively certain that they won't change much in a day.

That 4-5 second range is a lot though. I'd expect closer to 2 second mark for to grab a custom list. Might be understandable if it was Next Episode / In-Progress as those lists involve a lot of look-ups and calculations but not for a custom list. Custom lists are just a list of IDs essentially.

As these particularly long lists? One thing I noticed with all of them is that they all have random sorting applied. Is there any difference unsorted? Though really I'm just spit-balling here. Random shuffle should be fast for sorting a list. 

It seems most likely the issue is simply one of connection speed to Trakt as everything else appears to be working fine.

EDIT: Just tested one of my own lists that I generate using MDbList and it is only taking me ~0.6s to retrieve from Trakt, so I'd say definitely you have some weird connection issue with Trakt going on at the moment. 

```
DIRECTORY TIMER REPORT
info=trakt_userlist&list_name=Best%20Movies%20Last%20Decade&list_slug=best-movies-last-decade&owner=true&plugin_category=Best%20Movies%20Last%20Decade&user_slug=jurialmunkey
------------------------------
get_list       :   0.575 sec
```

EDIT2: I tried loading a ridiculously massive list (6000+ movies) and it took 20 seconds to retrieve, so size is going to matter a lot here (my list above is limited to 70 movies hence fast).

I might add in an option to always cache user lists which will avoid this scenario.

**Comment by jurialmunkey** [comment] 2022-08-29 13:15
@Tee77 - Please try v4.11.5 -- It adds an option to cache Trakt lists you own for 24 hours (on by default now). It should make a big difference to reloading these lists. Only downside is that if you add/remove items from a custom list you will need to wait a day to see the changes (or go into the settings and turn the option off temporarily to reload them).

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.11.5

**Comment by ghost** [comment] 2022-08-29 13:21
Really useful feedback.

> Are these particularly long lists? Is there any difference unsorted?

Largest list is 200, the rest are between 80-110. Before generating the second log, I capped all custom lists that I own to 20 items via mdblist and widget refreshes were still taking a while to retrieve from trakt. I actually tested lists as unsorted as well and there wasn't any significant difference.

> I'd say definitely you have some weird connection issue with Trakt going on at the moment

Yeah I think you're right. The way performance seemed to randomly drop out of nowhere would make sense.

**Comment by ghost** [comment] 2022-08-29 13:21
Nice. I'll try v4.11.5 now.

**Comment by ghost** [comment] 2022-08-29 13:43
Dude...you're awesome. That's taken a good couple of seconds off the overall widget refresh time, feeling much closer to how it used to perform. I still think you're right though about the weird trakt connection issue though, given your own Trakt retrieval times, so if I get that sorted performance should be even better. I'm happy though, thanks!

**Comment by jurialmunkey** [comment] 2022-08-29 13:57
No worries. And yeah everything seems to be pointing towards a connection issue with Trakt of some sort. The get_list part is one of the areas where specs don't really matter, Most of that time is simply sitting idle waiting for a server response because there's not much else TMDbH can do in the meantime until it has the list of items.

I'd say give it a week and likely it will resolve itself. If it is still a problem in another week we can revisit it. In the meantime at least this change with the caching should make the reload times a bit more bearable.

**Comment by ghost** [comment] 2022-08-31 17:31
Quick update...

Assuming this may be an issue with Trakt connection, I left both Trakt Trending lists & Next Episodes as they were, but changed the other four widgets to use mdblist lists directly to see if it would speed things up - all limited to 100 items via mdblist, and cache custom lists enabled. 

Rebooted then started/ stopped a live tv channel and waited for widget refresh (twice).

http://ix.io/49gB

get_list times for some mdblist widgets seem decent, but others are slower than I would've thought given they're cached. Wonder if this isn't a Trakt issue after all? Possibly an issue with my network, but saying that, AH2 widget refreshes on my windows laptop are as fast as ever 

Anyway, this is just for info - refresh times are decent enough. Happy for you to close this.

**Closed as completed** 2022-09-05 00:50 UTC
Labels: bug
