### ISSUE TITLE
[Bug] Episode play from widget = kodi crash

### ISSUE THREAD

**Issue by henryjfry** [jurialmunkey/plugin.video.themoviedb.helper#60] opened 2020-01-26 14:22 UTC
With the newest version im having issues when I click on an episode in a widget it will reload the player choice dialog over and over again then when it stops and i can choose a player kodi will then crash.

It seems like the service addon is triggering this as I saw something in the logs with debug logging enabled but I cant figure out what is causing the player choice dialog to reload itself.

I think its partly because i have openmeta installed and its finding stuff in my library but it works perfectly fine when it is triggered externally from a context menu item.

**Comment by henryjfry** [comment] 2020-01-26 15:42
Ok so ive figured out how to stop the "Choose Players" window from triggering repeatedly which seems to be the cause of the crash i was experiencing.

In script.py ive made a modification to "def play(self)"

```
    def play(self):
	current_window = xbmcgui.getCurrentWindowDialogId()
        if not self.params.get('play') or not self.params.get('tmdb_id') or current_window in [10160]:
            return
        Player().play(
            itemtype=self.params.get('play'), tmdb_id=self.params.get('tmdb_id'),
            season=self.params.get('season'), episode=self.params.get('episode'))
```
So if the choose players dialog is visible it wont run the "play" routine again.

**Comment by SerpentDrago** [comment] 2020-01-26 16:18
I'm getting the issue to (only though skin info page or widget ) , default player set or not .  crash to desktop of kodi , happens after picking the player . 

It does NOT happen if i use tmdb helper directly (not though a skins information screen / widget )

**Comment by henryjfry** [comment] 2020-01-26 16:25
Yeah im getting it under the same circumstances.
Ive added some stuff to script.py to see whats going on

```
        elif self.params.get('play'):
	    xbmc.log(str(xbmcgui.getCurrentWindowDialogId())+'===>TMDB_HELPER_!!!!', level=xbmc.LOGNOTICE)
	    if xbmcgui.getCurrentWindowDialogId() == 10138:
	            self.play()
    	    if xbmcgui.getCurrentWindowDialogId() == 12000:
	            return
```
And it loops round over and over again, and it'll crash once it loops over once, im guessing because whatever information makes in into the second instance of the choose players window is now completely invalid.

But i cant figure out how to stop it from triggering play again.

**Comment by henryjfry** [comment] 2020-01-26 17:54
Ive reverted to version 2.2.32 which didnt have this problem.

**Comment by jurialmunkey** [comment] 2020-01-26 21:09
Debug logs would be useful please... Also a clear step by step to reproduce.

@henryjfry - Are you using latest git version? It is ahead of the repo version by quite a few revisions.

@SerpentDrago - Can you confirm if this is also happening with latest **git** version? Git is v2.2.40, repo is only v2.2.34

**Comment by jurialmunkey** [comment] 2020-01-26 21:11
Also if the issue is still happening with v2.2.40 can you comment out this line and see if it still happens: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/container.py#L595

**Comment by henryjfry** [comment] 2020-01-26 21:16
I can get you some debug logs but it will need to be tomorrow.
I had been on 2.2.34 and I had also copied over the files from GitHub so up until updates made today basically. And it seemed to be the same issue. 
I can confirm that for you tomorrow when I reinstall the newer version.

I was looking to see what commits could have started that behaviour, could the change to the container (finish container) cause it to keep trying to play?

I'm not sure why it would but its my best guess.

I'll look at your suggestions as soon as I can and get back to you.

**Comment by henryjfry** [comment] 2020-01-26 21:19
But to reproduce it all I had to do was try and play an episode from my next up trakt episodes as a widget, wait for choose players to come up, wait till the busy dialog comes up again and the screen flashes as it creates or reloads the choose players dialog then click play with any add-on, Kodi crashes and restarts.

**Comment by henryjfry** [comment] 2020-01-26 21:27
By the way, that's exactly the commit I think caused the problem:

https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/container.py#L595

Or something about it anyway, it like it plays and then it tries to keep playing. And I think it was something to with "next item in playlist", something like that?

**Comment by jurialmunkey** [comment] 2020-01-26 22:05
@henryjfry - What platform are you on that's experiencing the crash? Win? Mac? LibreELEC? Android? Linux?

**Comment by henryjfry** [comment] 2020-01-26 22:23
Osmc on a vero4k. So Linux.
I can post full logs for you tomorrow

**Comment by linelock** [comment] 2020-01-26 22:25
Hi, I've been having this same issue. my debug Kodi.log is here.
https://pastebin.com/gPSCfHkM
The problem remains with v2.2.40 of tmdb helper. 
I'm running kodi 18.5 with auramod skin on ubuntu 19.10

**Comment by linelock** [comment] 2020-01-26 22:34
commenting out line 595 of container.py does seem to resolve the issue.

**Comment by jurialmunkey** [comment] 2020-01-26 23:05
@linelock - Thanks for testing/log/confirming.
Yes, 595 definitely seems to be the cause. I added it to deal with a bug in `.strm` files, but crashing is a more serious issue! I've commented out that change in v2.2.41 until I find a better solution for `.strm` bug. 

At least this way we won't get crashes and the player function will actually work!

**Comment by drinfernoo** [comment] 2020-01-26 23:52
@jurialmunkey You're referring to the `setResolvedUrl(...)` line?

**Comment by jurialmunkey** [comment] 2020-01-27 06:21
> 
> 
> @jurialmunkey You're referring to the `setResolvedUrl(...)` line?

Yeah.

I'm not actually resolving a url with the player function because we aren't always resolving (e.g. if we want to search an addon instead or if the addon first needs to load a directory of sources). 

Inside the plugin it's fine, but for a strm file Kodi expects a resolved url or it gives a "Playlist can't find next item to play" error. So to suppress that error, I just pass Kodi a blank "resolved" url - but that was causing crashes in the widgets.

Hoping my latest update will fix both issues.

**Comment by jurialmunkey** [comment] 2020-01-27 06:22
@linelock @henryjfry - Can you test latest update and make sure my latest addition hasn't reintroduced the crash issue (it shouldn't do but testers are always useful to confirm).

**Comment by linelock** [comment] 2020-01-27 06:32
@jurialmunkey Just checked and playing episodes from a widget is working in v2.2.44 
Thanks for this.

**Comment by jurialmunkey** [comment] 2020-01-27 07:20
> 
> 
> @jurialmunkey Just checked and playing episodes from a widget is working in v2.2.44
> Thanks for this.

Okay Awesome! Thanks for testing. 

That'll solve both issues then 😁

**Closed by jurialmunkey** 2020-01-27 07:20 UTC
