### ISSUE TITLE
playing .strm files is a lot slower than the same library files played via a context menu command

### ISSUE THREAD

**Issue by henryjfry** [jurialmunkey/plugin.video.themoviedb.helper#77] opened 2020-02-05 20:44 UTC
As per the title i've set up some of my shows in the library as "strm" files in the addon_data folder for tmdbhelper.  And i've found that when i click to play one of the strm files it takes about 2 times as long for the choose player window to appear than if i play the same file via a context menu item. So about 10 seconds via the normal "play" route vs about 5 seconds via a context menu item.

My context menu item is triggering something along the lines of "url = 'plugin://plugin.video.themoviedb.helper?info=play&amp;query=' + str(i['show']['title']) + '&amp;type=episode&amp;season=' + str(s['number']) + '&amp;episode=' + str(e['number'])
xbmc.executebuiltin('RunPlugin(%s)' % url)"

So it has to query the show tmdb_id after it runs, but it still runs quicker than the built in "play" route.

Ive been looking at the container.py and script.py play routes and from what i can tell it seems to trigger the same lookups of tmdb_id more than once, irrespective of whether or not it actually needs to lookup any information to identify the file.

I modified a couple of the strm files so that they used the "query" instead of "tmdb_id" and the script "args" were still coming back with the tmdb_id so its definitely doing a preliminary lookup and then another lookup prior to deciding to launch the file.
The busy dialog will close and reopen or falter several times during the normal play route whereas the "RunPlugin" version will cycle smoothly until the choose player window opens.

Ive tried to figure out exactly what route it follows when you click "play" on a file but i think the interaction of list_play, with the service play, service.py and script.py is tripping me up.  I cant figure out at which point it decides to start looking up files even if it has all the required information in the url.

**Comment by henryjfry** [comment] 2020-02-05 21:05
I think it is something to do with the "xbmcplugin.setResolvedUrl(self.handle, True, ListItem().set_listitem())" step

**Comment by jurialmunkey** [comment] 2020-02-05 22:02
Script doesn't do any lookups other than lookup detailed info if you pass tmdb_id. All strm files pass tmdb_id

When you run play command it pass params to the plugin.py tmdb_id lookup function. If you have a tmdb_id in param, that function just returns the tmdb_id and doesn't do any lookup:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/plugin.py#L58-L63

The ResolvedURL Listitem doesn't do any lookups. It just sets the ListItem's dictionaries to the ListItem. The dictionaries are empty at that stage because nothing is passed to the function:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/blob/master/resources/lib/listitem.py#L213-L236

The Player function doesn't do any tmdb_id look-ups. It just rejects if a tmdb_id is not passed to it. All strm files have tmdb_id in their path, so no look-ups are done other than looking up the details for that item (and also checking if it is in the library).

The function runs exactly the same whether it is from a strm or a tmdb listitem. The only addition is the setResolvedUrl which does nothing other than create an empty listitem. Any speed difference is related to Kodi and not the plugin.

**Comment by henryjfry** [comment] 2020-02-19 19:47
Hey

So ive been investigating this issue on my own and I have discovered some stuff with regard to the slow resolution/multiple triggering of the "RunPlugin" command when i try to launch a tmdbhelper plugin url from a strm file or a m3u playlist.

Firstly I should say that this isnt a tmdbhelper bug as you pointed out, i think its related to this kodi issue:
https://github.com/xbmc/xbmc/issues/16385

If you want to replicate it all you would need to do is add a tmdhelper url to a m3u playlist and try and play a link (eg plugin://plugin.video.themoviedb.helper?info=play&amp;type=episode&amp;tmdb_id=95&amp;season=1&amp;episode=1) and it will take a while to load and also reload the player select dialog multiple times and then probably crash when you click on a player (not sure if you need to add "xbmcplugin.setResolvedUrl(self.handle, True, ListItem().set_listitem())" to container.py before that happens but without it, it would throw the playlist error which is undesirable in and of itself).

Anyway I think the issue is related to "xbmcplugin.setResolvedUrl(self.handle, True, ListItem().set_listitem())" which is needed to prevent the error but seems to cause the "RunPlugin" command to restart when it resolves the url.
I think this is connected to the xbmc error I linked above and I suspect when it is told to resolve an empty url or otherwise unresolvable url (eg a plugin url) kodi decides to start again up to the count of 5 as per PlayListPlayer.cpp

What I have found is that for a non addon play command (ie a strm file, or m3u playlist entry) 
xbmcplugin.endOfDirectory(self.handle, updateListing=False, cacheToDisc=False) seems to be more reliable rather than setResolvedUrl.
For m3u playlists this will still seem to trigger again, I have therefore setup my own play method which will write a file and not re-run the command if this file exists. I did attempt a lock-file method but I couldn't get it to lock/unlock reliably.

So would altering the "play" method to use endOfDirectory for anything but addon listitems work and/or would you know how to prevent the addon from re-running if the kodi issue causes the play command to be triggered multiple times (bearing in mind that it would need to setResolvedUrl or endOfDirectory each time its re-run or else kodi will throw the playlist error)?

Here is my alternate play method which works from an m3u playlist (basically with a lock-file to prevent rerunning, and you can see where i've added log messages to track how the RunPlugin command keeps repeating which needs to be prevented to stop kodi crashing).
Maybe you know a better way to create a temporary lock to prevent it rerunning, maybe an environment variable which could be wiped once its successfully loaded the player dialog?

I should mention that from a strm file this method is also just that bit quicker that your method and the busy dialog doesnt disappear while its running.

```
        if self.params.get('info') == 'play2':
#url = plugin://plugin.video.themoviedb.helper?info=play2&amp;type=episode&amp;tmdb_id=95&amp;season=1&amp;episode=1
		import os
		addon_handle = self.handle

		xbmc.log(str(xbmcgui.getCurrentWindowDialogId())+'===>TMDBHelper', level=xbmc.LOGNOTICE)

		if os.path.exists('/home/osmc/' + self.paramstring):
			xbmc.log('File Exists Exiting '+'===>TMDBHelper', level=xbmc.LOGNOTICE)
			xbmcplugin.endOfDirectory(addon_handle, updateListing=False, cacheToDisc=False)
			exit()

		xbmc.executebuiltin('ActivateWindow(busydialognocancel)')

		type = self.params.get('type')
		episode = self.params.get('episode')
		season = self.params.get('season')
		year = self.params.get('year')

		params = self.params
	      	if self.params.get('type') == 'episode':
        		params = self.params.copy()
	        	params['type'] = 'tv'
	        tmdb_id_no = self.get_tmdb_id(**params)
	
		xbmc.log(str('/home/osmc/' + self.paramstring)+'===>TMDBHelper', level=xbmc.LOGNOTICE)

		if not os.path.exists('/home/osmc/' + self.paramstring):
			from resources.lib.player import Player
			f= open('/home/osmc/' + self.paramstring,"w+")
			xbmcplugin.endOfDirectory(addon_handle, updateListing=False, cacheToDisc=False)
			if type == 'episode':
				Player().play(itemtype='episode', tmdb_id=tmdb_id_no, season=season, episode=episode)
			if type == 'movie':
				Player().play(itemtype='movie', tmdb_id=tmdb_id_no)

			"""
			xbmc.log(str('While...')+'===>TMDBHelper', level=xbmc.LOGNOTICE)

			while not 'Play with ' in xbmc.getInfoLabel('System.CurrentControl') or not 'Search ' in xbmc.getInfoLabel('System.CurrentControl'):
				xbmc.sleep(1000)
				xbmc.log(str(xbmc.getInfoLabel('System.CurrentControl'))+'===>TMDBHelper', level=xbmc.LOGNOTICE)
				if 'Play with ' in xbmc.getInfoLabel('System.CurrentControl'):
					break
				if 'Search ' in xbmc.getInfoLabel('System.CurrentControl'):
					break

			xbmc.log(str('After While ')+'===>TMDBHelper', level=xbmc.LOGNOTICE)
			"""
			f.close
			try:
				os.remove('/home/osmc/' + self.paramstring)
			except:
				pass
			xbmc.executebuiltin('Dialog.Close(busydialognocancel)')

        return

```

**Comment by jurialmunkey** [comment] 2020-02-20 11:39
I was actually using endofDirectory before but apparently it causes crashes for some systems, which is why I switched to using a dummy resolvedurl.

Unfortunately I haven't discovered a reliable way to suppress the "next item in playlist failed to play" issue - setting the dummy resolvedurl is the least worst out of the two above methods because at least it doesn't trigger a crash and it is better than getting the playlist error.

**Comment by jurialmunkey** [comment] 2020-02-20 11:59
@henryjfry - Okay I've added endofdirectory method back in to suppress next playlist item error. Now it is optional to choose between resolvedurl or endofdirectory (in expert settings), for those that the endofdirectory method causes crashes for. Can you test and see if it is working properly for you?

**Comment by henryjfry** [comment] 2020-02-20 18:57
I can confirm that for STRM files the endofdirectory method is working and loads as quickly as my own method.

For m3u playlists I am still getting the issue where it reloads multiple times, but its not as slow as before, however it will still crash.

So for general use this change is probably fine, for my use i will probably still use my own alternate method. I have a service plugin setup to write what i watch to a playlist so if kodi crashes or i otherwise need to restart I can reload whatever i was watching without having to browse for it.
So i want a method which will play from a m3u playlist and not suffer from this multiple RunPlugin call issue.

I suspect that isn't a concern though for 99% of your userbase so this update is probably acceptable for the majority.

**Comment by jurialmunkey** [comment] 2020-02-20 20:50
Is this m3u issue when trying to play a playlist of library strm files?

**Comment by jurialmunkey** [comment] 2020-02-20 22:04
I can't actually reproduce this issue on my end but I do have an idea for how to address it. I'll keep you posted.

**Comment by henryjfry** [comment] 2020-02-21 10:30
Ok cool. 

I know that openmeta didnt/doesn't have this particular issue although I can't figure out how it circumvents it. But it may be worth looking at base_play in openmeta?

**Comment by jurialmunkey** [comment] 2020-02-21 11:31
@henryjfry - Can you test this branch and see if it solves the issue:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/tree/player-testing

> I know that openmeta didnt/doesn't have this particular issue although I can't figure out how it circumvents it. But it may be worth looking at base_play in openmeta?
Yeah I couldn't quite figure it out either

**Comment by jurialmunkey** [comment] 2020-02-21 11:36
Sorry, re-download that branch as I accidentally left something in that I shouldn't have.

**Comment by henryjfry** [comment] 2020-02-21 18:18
Ok so i've downloaded the test branch and for strm files, with islocal=true they play fine.

For the playlist entries it doesnt reload the player select dialog over itself however if I exit back out it will launch the player select again, and if you keep exiting it will reload it 5 times before it stops.
When it loads and I select a player rather than exiting out kodi will crash, i imagine because it immediately tries to reload the dialog whilst also trying to load the player.

So i think it needs some persistence once you exit or select a player to make sure it doesnt try to reload the player select dialog?

**Comment by henryjfry** [comment] 2020-02-21 19:21
Sorry I obviously didnt try to play the strm file, when i actually try to play it with "&amp;islocal=true" it causes kodi to crash also.
Without it the strm file will give the playlist error but it will load a player when you select it.

**Comment by jurialmunkey** [comment] 2020-02-21 22:25
@henryjfry - Ah, I had a feeling that I maybe made it worse with that one.

Can you try the latest commit to that player-testing branch? I think this method should work.

Also can you test with both the resolvedurl and the endofdirectory method? There's a toggle in the expert settings of the plugin to switch between both.

**Comment by henryjfry** [comment] 2020-02-22 11:36
Ok so ive tested with the new testing version and I can confirm that from strm files it is working as expected, doesnt reload on exit and doesnt crash when i select a player from the dialog.

From a playlist it is giving me a playlist error message but it will load the select dialog and I can then select a player.

So for the playlist i added the "self.addon.getSettingBool('strm_method_resolvedurl')" test to "def play_islocked() in order to suppress the error:

```
    def play_islocked(self, lock=None):
        for k, v in self.params.items():
            lock = '{}.{}={}'.format(lock, k, v) if lock else '{}={}'.format(k, v)
        cur_lock = xbmcgui.Window(10000).getProperty('TMDbHelper.Player.ResolvedUrl')
        if self.addon.getSettingBool('strm_method_resolvedurl') and cur_lock == lock:
            xbmcplugin.setResolvedUrl(self.handle, True, ListItem().set_listitem())
        else:
            xbmcplugin.endOfDirectory(self.handle, updateListing=False, cacheToDisc=False)
        if cur_lock == lock:
            return cur_lock
        xbmcgui.Window(10000).setProperty('TMDbHelper.Player.ResolvedUrl', lock)
```
Which worked and it will now load the player select dialog without giving an error. 

And i tried both "setResolvedUrl" and "endOfDirectory" and i can confirm they both work, with "setResolvedUrl" appearing to be marginally faster.

So i think you need to add a step to "play_islocked" to resolve a url to prevent the error message, would there be any way to only resolve a url once, like on the 5th iteration?
My thinking is that to prevent the error it might work on the last time rather than having play_islocked resolve a url each of the 5 times it is triggered (or 4 with cur_lock == lock)?
Only resolving it the first and the last time would speed things up a little bit, if it wouldn't cause an error on the 2nd,3rd and 4th loops?

**Comment by henryjfry** [comment] 2020-02-22 11:40
Also is there anyway you could get the busy dialog to remain on screen until the player dialog is loaded?

Its not particularly important I just like to know its still working.  Currently for a strm file the busy dialog disappears for most of the loading time so i'm never sure if its still working or not until the busy dialog reappears a second or two before the dialog loads.

**Comment by jurialmunkey** [comment] 2020-02-22 12:48
Okay, merged to master with setresolvedurl now in the play_islocked check.

I think it probably needs to resolve *every* time to ensure we don't get the next item failed to play error. 

I think on latest master the busy dialog is working a bit better.

**Comment by henryjfry** [comment] 2020-02-22 15:38
Ok so with the new main version I find it to be a good bit slower than the testing version I tested earlier.
Also the busy dialog still will disappear and reappear so those changes dont really appear to have worked.

So from looking at the updates to 2.2.72 the only thing i can see which would significantly impact the speed is the "with busydialog" parts.  So given that with this change the busy dialog is still vanishing i would maybe just get rid of that?

So the testing version with the additional setreslovedurl in the play_islocked?

**Closed** 2020-03-11 00:15 UTC
Labels: enhancement
