### ISSUE TITLE
[Feature] Next Episodes - Option to Sort Episodes Airing Today to Top

### ISSUE THREAD

**Issue by AakashC2020** [jurialmunkey/plugin.video.themoviedb.helper#794] opened 2022-07-09 10:07 UTC
### Describe the feature that you'd like

Hi @jurialmunkey,

Just like the title says, could you add an option for TV Shows -> Next Episodes to Sort Episodes Airing Today to Top of the list?

### Why is this feature needed? What problem does it solve?

This feature will be beneficial as the latest episodes airing today will be shown at the top of the list, so that we can know when a new episode has been released in case we have finished watching all the previous episodes of that particular TV Show.

### Checklist

- [X] I have searched the issues and this feature has not been requested.
- [X] I have updated TMDbHelper to the most recent version.

**Comment by jurialmunkey** [comment] 2022-07-09 10:32
You already can.
TMDBh settings > widgets > next episodes sort method

Set to airdate

**Comment by AakashC2020** [comment] 2022-07-09 13:48
> You already can. TMDBh settings > widgets > next episodes sort method
> 
> Set to airdate

Hi @jurialmunkey,

I already tried that option but that's not exactly what I wanted. The feature that I wanted is that an Episode which is airing on the current date will appear on Top of the Next Episodes list and later on will move to it's actual position as per Recently Watched once the day is over. It's already present in another video addon but I wanted it to be implemented in TMDB Helper. It's okay if this can't be done. I just wanted to know if this is possible in TMDB Helper.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment] 2022-07-09 15:25
Why would you want that to happen? Why would you skip ahead of where you're up to?

**Comment by AakashC2020** [comment] 2022-07-09 16:25
> Why would you want that to happen? Why would you skip ahead of where you're up to?

Hi @jurialmunkey,

I think I'm not able to explain properly. Okay I'll give an example. Suppose I've watched Ms. Marvel upto episode 5 and episode 6 has not released yet. So what I'll see at the top of the next episodes list is the next show that I'm watching which is say Obi Wan Kenobi. Then I watch another show say Stranger Things. So now Stranger Things' next episode comes at the top of the list. Now next Wednesday when Ms. Marvel next episode releases it will show between Stranger Things and Obi Wan Kenobi as per Recently Watched. However, in that other video addon which has this feature it will show Ms. Marvel's next episode at the top of the list on the release day instead of Stranger Things when the option is activated in the settings. That's how I will come to know that a new episode for Ms. Marvel has released. This helps when there are a lot of on going shows in the next episodes list. Once the day is over then Ms. Marvel will again move to it's designated old position that is between Stranger Things and Obi Wan Kenobi. Hope this is clear now.

Thanks and Regards,
Shibaji Chattopadhaya.

**Comment by jurialmunkey** [comment] 2022-07-10 04:54
Ah okay I understand now! That's actually a really excellent idea!

Could you try v4.10.8?
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases/tag/v4.10.8

There's two additional sorting settings: "todays" and "lastweek". 

- Todays puts episodes airing today at the front. It is actually checks yesterday+today to make sure we definitely get the episodes that aired in last day. i.e. checks both 24hrs before and 24hrs after current utc time.
- LastWeek puts episodes airing in the last 7 days to the front. Same idea just a longer release window.


It _should_ work correctly. However, I don't have anything airing today, so all my tests involved larger date ranges. But it appears to be working and theoretically should work correctly for todays.

**Comment by AakashC2020** [comment] 2022-07-10 10:33
Hi @jurialmunkey,

Thank you so much!
I checked with dummy test cases by adding to Trakt random episodes and both "todays" and "lastweek" options appear to be working fine. However, I have a small request, is it possible to sort by the latest released episode of a TV Show at first in the "last week" option? For example, suppose I watched Evil first and then Ms. Marvel. However, Ms. Marvel latest episode released 3 days back, whereas Evil latest episode released today. In this case is it possible to show Evil latest episode at the top of the list instead of Ms. Marvel which is currently the case, as the most recently released episode is of Evil and not Ms. Marvel? Kindly advise.

Also, 1 more thing I noticed is that for some newly released TV show episodes, the image is not showing under Next Episodes list. For example, see the below 2 screenshots, 1 is from TMDB Helper and another from a different video addon. In TMDB Helper the latest episode image for Ms. Marvel is not updated, whereas for the other video addon it is updated.

In TMDB Helper:
![IMG20220710151311](https://user-images.githubusercontent.com/65297828/178141199-a7fbd6d3-d7ee-429e-8fcd-ee4bde4d0450.jpg)

In the other video addon:
![IMG20220710151334](https://user-images.githubusercontent.com/65297828/178141212-b5c7cd27-db31-4e8a-a3fc-8c9d53dd0ae4.jpg)

Should I create a separate issue ticket for this? Please suggest.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment] 2022-07-10 12:44
I can add it but it will be slightly slower because need to re-sort the list partition after it is made - but yeah makes sense to do it that way.

Re images - check that it happens in Estuary. AH2 has some extra conditions to hide spoilers. Also check your next episodes thumb setting in tmdbhelper - it might be set to fanart not thumb.

Also note that tmdbh caches details and artwork for 2 weeks, so if you retrieved that item before the thumb was available then it will be cached. You would need to refresh details manually from the context menu if you want to override the cache expirary.

**Comment by AakashC2020** [comment] 2022-07-10 14:39
Hi @jurialmunkey,

Reg. sorting, slightly slower is fine (if not too slow) because it'll be even better if it is sorted that way.

Reg. the images I checked in Estuary and it's the same case. I then checked in TMDB Helper settings for Next Episodes and they are set to thumb, not fanart. I also refreshed the details and artwork for that episode (Ms. Marvel Season 1 Episode 5) and it's still not showing the thumb. The surprising thing is that in both TMDB and Trakt websites the thumb for that episode is updated and in that other video addon that mentioned it's showing correctly. The issue is only with TMDB Helper. Could you please check from your end and kindly advise?

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment] 2022-07-10 16:49
Sorting by date for lastweek added.

I'm unable to reproduce the thumb issue. Thumb works fine for me:

![Honeyview_screenshot00036](https://user-images.githubusercontent.com/4618719/178154041-2dcdcc00-42e6-4851-a54c-f2c820214b44.jpg)

**Comment by AakashC2020** [comment] 2022-07-10 18:19
Hi @jurialmunkey,

Thanks for adding the sort feature!

Reg. the image thumb issue I can confirm that it's a TMDB cache issue. I finally resolved it by first deleting the TMDB cache from TMDB Helper settings and then by manually refreshing the details of the episode. The image thumb updated successfully after this. See screenshot below. Is there any alternative way to refresh the thumbs correctly apart from deleting the TMDB cache? Please advise.

![IMG20220710234456](https://user-images.githubusercontent.com/65297828/178157167-c1b08509-0f40-499c-8b37-6c6430bb0e5d.jpg)

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment] 2022-07-11 01:25
You can refresh details from the context menu for the item (next to the manage artwork option).

**Comment by AakashC2020** [comment] 2022-07-11 04:09
> You can refresh details from the context menu for the item (next to the manage artwork option).

Hi @jurialmunkey,

I already tried that multiple times, but it alone didn't work. Only when I deleted the TMDB cache from TMDB Helper settings first and then clicked on refresh details from the context menu of that episode it worked, and the correct image updated. What might be the issue? Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment] 2022-07-11 05:14
Can you grab me a screenshot of the context menu item you're using to refresh? I assume it's the correct one but just want to double check before I go bug hunting!

**Comment by AakashC2020** [comment] 2022-07-11 05:43
> Can you grab me a screenshot of the context menu item you're using to refresh? I assume it's the correct one but just want to double check before I go bug hunting!

Hi @jurialmunkey,

Following are the requested screenshots of the context menu items that I tried to refresh, i.e. both Refresh Details and Refresh All Artwork. None of them worked until I deleted TMDB cache from TMDB Helper settings first and then clicked on Refresh Details again.

![IMG20220711110949](https://user-images.githubusercontent.com/65297828/178196426-5027ca74-c582-4759-b70e-a64c96a50298.jpg)

![IMG20220711111000](https://user-images.githubusercontent.com/65297828/178196447-5e24976b-7747-4099-8028-0203a8b5426b.jpg)

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment] 2022-07-11 06:30
Okay, I think v4.10.10 should fix the refresh issue. Though I doubt you have anything to test with now!

Cache timestamps suggest it is working correctly so I'm fairly sure I've got it all working properly now (difficult to test as it needs deliberately out of date data cached!).

Hopefully I didn't mess up the manual artwork code as that's intertwined in there and it's a bit delicate.

**Comment by AakashC2020** [comment] 2022-07-11 07:42
Hi @jurialmunkey,

Yes, I didn't find anything particular to test the fix.
Nevertheless, thank you so much for your prompt action regarding the same! 🙂

Thanks and Regards,
ShibajiCh.

**Comment by jurialmunkey** [comment] 2022-07-11 08:13
I'm fairly sure it's fixed so going to close this one. Let me know if you come across the issue again and refreshing details doesn't work.

**Closed as completed** 2022-07-11 08:13 UTC
Labels: enhancement

**Comment by AakashC2020** [comment] 2022-07-11 08:31
> I'm fairly sure it's fixed so going to close this one. Let me know if you come across the issue again and refreshing details doesn't work.

Hi @jurialmunkey,

Sure. I'll let you know if I face such an issue again. Thanks again!

Thanks and Regards,
ShibajiCh.
