### ISSUE TITLE
[Log Spam] Trying to load setting definitions from old format...

### ISSUE THREAD

**Issue by tjamieg** [jurialmunkey/plugin.video.themoviedb.helper#55] opened 2020-01-24 17:37 UTC
```
2020-01-24 15:21:52.013 T:26452   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting definitions
2020-01-24 15:21:52.014 T:26452   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: trying to load setting definitions from old format...
2020-01-24 15:21:52.017 T:26452   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting values
2020-01-24 15:21:52.018 T:26452   DEBUG: CSettingsManager: requested setting (trakt_token) was not found.
2020-01-24 15:21:52.018 T:26452   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: failed to find definition for setting trakt_token. Creating a setting on-the-fly...
2020-01-24 15:21:52.023 T:26452   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting definitions
2020-01-24 15:21:52.023 T:26452   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: trying to load setting definitions from old format...
2020-01-24 15:21:52.027 T:26452   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: loading setting values
2020-01-24 15:21:52.028 T:26452   DEBUG: CSettingsManager: requested setting (trakt_token) was not found.
2020-01-24 15:21:52.028 T:26452   DEBUG: CAddonSettings[plugin.video.themoviedb.helper]: failed to find definition for setting trakt_token. Creating a setting on-the-fly...
2020-01-24 15:21:52.030 T:26452  NOTICE: [plugin.video.themoviedb.helper]
                                            Error: attribute of type 'NoneType' is not callable
2020-01-24 15:21:52.059 T:26452  NOTICE: Previous line repeats 8 times.
```

**Comment by jurialmunkey** [comment] 2020-01-24 22:30
Kodi Version?
OS?
Platform?

I don't get these errors on 18.5 on Windows or LibreELEC.

**Comment by jurialmunkey** [comment] 2020-01-24 22:49
@tjamieg can you test latest version (v2.2.36)? This issue is a known kodi bug that will be fixed in Matrix - but I'm hoping that this change I've made might reduce the log spam a bit.

**Comment by tjamieg** [comment] 2020-01-24 23:42
**Kodi Version:** 18.5
**OS:** Android (ARMV7A)
**Device:** Amazon Fire TV Stick 4K

Understood, will test latest version and get back to you.

**Comment by drinfernoo** [comment] 2020-01-25 00:00
@jurialmunkey, for more information, what is the "old" format, and how can we make sure we're using compatible formats for settings in the future?

**Comment by tjamieg** [comment] 2020-01-25 00:26
@drinfernoo I was wondering if it could have been referring to Python 2.7 and 3.0.

@jurialmunkey nixgates came across the same thing [here](https://github.com/nixgates/plugin.video.seren/issues/69) and there was also [this](https://github.com/xbmc/xbmc/issues/15252) on the XBMC github.

**Comment by jurialmunkey** [comment] 2020-01-25 00:37
> 
> 
> @jurialmunkey, for more information, what is the "old" format, and how can we make sure we're using compatible formats for settings in the future?

In Matrix, the format of Addon settings.xml has been changed to match Kodi's inbuilt setting format. The change allows for having settings "levels" (e.g. Basic, Advanced, Expert) just like Kodi settings (e.g. Interface settings etc.).

In Leia, there was an attempt to transition to this new format but it brought some issues that weren't discovered until after it was implemented and a fix wasn't able to be made in a point release.

There's info on the new format here:
https://kodi.wiki/view/Add-on_settings_conversion

**Comment by tjamieg** [comment] 2020-01-25 00:39
@jurialmunkey I just tested the latest version (v2.2.36) and the log is still very spammy.

**Comment by jurialmunkey** [comment] 2020-01-25 00:44
> 
> 
> @jurialmunkey I just tested the latest version (v2.2.36) and the log is still very spammy.

Yeah, it was a bit of a long shot. I'll have a read around and see if I can find anything else out.

Can you get me your settings.xml from `userdata/addon_data/plugin.video.themoviedb.helper/settings.xml` ? Before posting be sure to remove your OMDb and Fanarttv keys from the file.

**Comment by drinfernoo** [comment] 2020-01-25 00:45
@jurialmunkey I see! I'd never stumbled on that page, but always assumed it had to do with the change from `[sg]etSetting(...)` to `[sg]et[Type]Setting(...)`?

What happens in Leia if we start using that format?

**Comment by jurialmunkey** [comment] 2020-01-25 00:55
@drinfernoo - I'm not sure, I've never tried the new format but it's not recommended if the addon is meant to be compatible for both Leia and Matrix. The issue is that other bugs have been introduced as a result of the code for the new format.

**Comment by drinfernoo** [comment] 2020-01-25 01:13
Also @jurialmunkey, how the heck you do it, I dunno, but almost every single time I push to the repo, you make more updates within the hour 😅

**Comment by tjamieg** [comment] 2020-01-25 01:23
> 
> 
> > @jurialmunkey I just tested the latest version (v2.2.36) and the log is still very spammy.
> 
> Yeah, it was a bit of a long shot. I'll have a read around and see if I can find anything else out.
> 
> Can you get me your settings.xml from `userdata/addon_data/plugin.video.themoviedb.helper/settings.xml` ? Before posting be sure to remove your OMDb and Fanarttv keys from the file.

Here you go:
[settings.xml](https://paste.ubuntu.com/p/VSRWDHXB7n/)

**Comment by jurialmunkey** [comment] 2020-01-25 01:45
Thanks. I'm a bit stumped though, as there doesn't look to be anything wrong here. Same format as on my systems but I don't get this log spam. I wish I had an Android device to test as it seems limited to that platform.

I'll ask around the Kodi team to see if anyone else has any insight and I'll get back to you.

**Comment by jurialmunkey** [comment] 2020-01-25 22:01
@tjamieg - Can you try closing Kodi, delete the settings.xml file, restart Kodi, then reauthorise Trakt and see if you still get the log spam.

The log spam is apparently due to storing a setting which is not available in settings dialog. I've added a hidden setting for trakt_token to the settings dialog which I'm hoping will stop the errors. 

If this doesn't help, then it's unlikely there is anything else I can do about it.

**Comment by drinfernoo** [comment] 2020-01-25 23:43
@jurialmunkey That causes the "creating definition on the fly" message, but the one about the old format 🙃

**Comment by jurialmunkey** [comment] 2020-01-25 23:57
@drinfernoo - Are you getting this log spam too? Can you test latest version and see if that fixes it?  I wonder if making the setting visible will help...

**Comment by tjamieg** [comment] 2020-01-26 01:24
@jurialmunkey Hey guys, tried the latest version (2.2.40) and also tried deleting settings.xml and reauth-ing Trakt... but the issue STILL persists.

Also tried it on a build with some other add-ons, and after checking the debug log I realise that this issue is not just native to TMDb Helper; @drinfernoo's OpenWizard has it and so does @nixgates' Seren.

**Comment by drinfernoo** [comment] 2020-01-26 01:34
@tjamieg It's because all of those add-ons use the "old" settings format.

**Comment by jurialmunkey** [comment] 2020-01-26 03:46
Closing this issue as I don't think there is a solution until Matrix.

**Closed by jurialmunkey** 2020-01-26 03:46 UTC
Labels: bug
