### ISSUE TITLE
[Bug] Playlist can't find next item to play

### ISSUE THREAD

**Issue by newf276** [jurialmunkey/plugin.video.themoviedb.helper#52] opened 2020-01-22 16:17 UTC
When utilizing the Trakt portion of the TMDB Helper, adding Movies to my Trakt collection is successful, it correctly adds and remove successfully and updates the Kodi Library as it should. However for TVshows, they do not add to my Trakt Collection, and they are not added to the Kodi Library like it does when adding Movies to collection in Trakt. TVShows that are already in my collection and are displayed in my Kodi Library do not remove when selecting remove from Trakt Collection. Hence it seems TV Shows do not add or remove when utilizing context add/remove to Trakt Collection. Here is debug: http://paste.kodi.tv/qesinaqihu

**Comment by jurialmunkey** [comment] 2020-01-22 21:28
@newf276 - I think this bug should be fixed now. Can you test 2.2.33?

**Comment by newf276** [comment] 2020-01-22 22:13
> @newf276 - I think this bug should be fixed now. Can you test 2.2.33?

Fixed, recommend closing. Thanks for the quick fix on this. Curious, is there a reason I always get Playlist error: can't find next item to play. I do not get this in openmeta etc.. I am not using an external player, so I should not need player core.xm file?

**Comment by jurialmunkey** [comment] 2020-01-23 06:04
Is this error when you click something in the library? What steps to reproduce?

**Comment by newf276** [comment] 2020-01-23 06:20
This error is when I select from the Kodi library, no matter what I select meaning a show or movie.  In the top right corner I get the Playlist can't find next item to play, but the item I selected always triggers the player dialogue, and I select one of the default TMDB Helper players and it plays.Just I get this error notification regardless. Perhaps it is because t=when adding to the Kodi library from the TMDB helper plugin, the plugin does not automatically create a video playlist file in the Playlist/vide folder, ie. video.xml?

**Comment by jurialmunkey** [comment] 2020-01-23 08:16
@newf276 - Can you test latest? I'm pretty sure I've fixed the playlist error.

**Comment by webmaher** [comment] 2020-01-23 11:09
I can confirm no more error, well done maestro :-)

**Comment by newf276** [comment] 2020-01-23 20:06
> @newf276 - Can you test latest? I'm pretty sure I've fixed the playlist error.

Just tested with with lates, and you are correct, the playlist error is fixed.  Thank you very much for the superb effort on this exceptional Addon, it is such an amazing plugin, and will become a favourite by everyone I am certain. 🥇

**Comment by jurialmunkey** [comment] 2020-01-27 05:28
Re-opening this issue as the Playlist can't find next item bug will be back since I needed to revert those changes.

**Comment by jurialmunkey** [comment] 2020-01-27 07:21
@newf276 - Can you test latest version and confirm that I haven't re-introduced this bug and all is working correctly with `strm` in library? Seems to be working correctly from my end but good to have someone confirm.

**Comment by newf276** [comment] 2020-01-27 17:34
Ack double check and get back to you soon.

**Comment by newf276** [comment] 2020-01-27 17:40
> @newf276 - Can you test latest version and confirm that I haven't re-introduced this bug and all is working correctly with `strm` in library? Seems to be working correctly from my end but good to have someone confirm.

Just tested lates version, error is not present, seems to be working correctly.

**Comment by jurialmunkey** [comment] 2020-01-27 21:32
Thanks so much for testing and confirming. So glad that both these bugs are now resolved! 😁

**Closed by jurialmunkey** 2020-01-27 21:32 UTC
