### ISSUE TITLE
"Your next episode" causing kodi to crash

### ISSUE THREAD

**Issue by GodsLikelyMe** [jurialmunkey/plugin.video.themoviedb.helper#680] opened 2022-03-16 06:23 UTC
Sorry, but back again. New issue with "Your next episode" section causing kodi to crash and force close when I try to open the section or when I try to add it as a widget. I downgraded tmdb helper to 4.4.0 from the kodi repo and it worked fine. I then tried to update again and it broke again. 

Installed on a fire tv
Kodi 19.4
Tmdb Helper 4.6.37

Log
https://paste.kodi.tv/kusewuzosu.kodi

**Comment by jurialmunkey** [comment] 2022-03-16 06:47
Can you get me a log with debug logging enabled and then try to open Next Episodes from inside TMDbHelper. I can't see much in the log at the moment, so hopefully debug logging will be a bit more revealing.
Kodi Settings > System > Enable debug logging

**Comment by GodsLikelyMe** [comment] 2022-03-16 07:08
Here you go.

https://paste.kodi.tv/woluhetewa.kodi

The crash take a bit to happen. The loading icon just spins till it freezes and kodi crashes.

**Comment by jurialmunkey** [comment] 2022-03-16 08:22
Hmm, I'm really not sure what the cause is. 

Can you close Kodi and delete everything in the tmdbhelper addon_data folder except `settings.xml` and the players folder (just so you don't need to do setup again). 
`kodi/userdata/addon_data/plugin.video.themoviedb.helper/`

Basically I want to make sure all the caches and logs etc. are properly deleted to force them to be recreated -- some type of corruption is all I can think of.

**Comment by GodsLikelyMe** [comment] 2022-03-16 08:59
No luck... I'll try another fresh install of kodi when I have a bit of time and start off with only installing tmdb to see if I can get it working. In the meantime, I'll downgrade to 4.4.0  

Thanks very much for trying to help figure it out. I'll report back with any results I get.

**Comment by jurialmunkey** [comment] 2022-03-16 09:06
> No luck... I'll try another fresh install of kodi when I have a bit of time and start off with only installing tmdb to see if I can get it working. In the meantime, I'll downgrade to 4.4.0
> 
> Thanks very much for trying to help figure it out. I'll report back with any results I get.

It was a bit of a long shot. 

Do you know approximately what version the problem started happening?

**Comment by GodsLikelyMe** [comment] 2022-03-16 09:20
Not really sure. I did a fresh install when I reported my first issue on 4.6.32, but I wasn't able to check anything since I couldn't authorize trakt, but the reason why I had to do a fresh install was because kodi kept crashing a minute or so after opening it and I had the next episode set up as a widget. I never really tried to look into the reason, but maybe that was it. I don't remember what version I was on before I wiped though. And I'm not sure, but I think I had just updated to kodi 19.4 right before the issues started happening.

**Comment by GodsLikelyMe** [comment] 2022-03-16 11:48
Ok, so I went down a bit of a rabbit hole testing versions and found where it starts crashing. I first started with 4.6.0 and that didn't work, so I went to 4.5.0 and that did. After that I started with 4.5.10, 4.5.20, and so on till it started crashing at 4.5.70. From there I tried each one from 4.5.61 to 4.5.65 and that is where the crashing starts. So every versions up to 4.5.64 works and crashes at .65. 

Hope that can shed some light.

**Comment by jurialmunkey** [comment] 2022-03-16 23:46
Thanks, that's really useful information! I'll have a dig back through the commits around then and see if I can find anything that might the cause. That'd be around when I switched to the item builder, so I'm guessing that there is one particular show or episode with something unusual in it that is causing a problem.

Could you download the version from the testing branch and then get me a log (just normal not debug) using that version:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/archive/refs/heads/testing.zip

It won't fix it but I added a lot of logging of every step of the process, so it will give an indication of exactly where in the code it is getting up to before the crash and which area needs attention. It should also indicate which specific show/episode is the culprit (if it is getting that far).

**Comment by GodsLikelyMe** [comment] 2022-03-17 00:49
Here you go.
https://paste.kodi.tv/pocukejewe.kodi

Could this be device specific? I ask b/c I have pretty much the same set up and same shows on my pc and have no issues with 4.6.38. I also saw someone on reddit post about a similar issue (they didn't specify if they think its tmdb) even after doing a clean install like I did and using a fire cube with also close to the same set up.

**Comment by GodsLikelyMe** [comment] 2022-03-17 01:33
Ok so I restored my working build with 4.5.64 on my fire stick 4k max (not the fire tv I'm having issues with) and then updated it to 4.6.38 and it took forever to load, but it didn't crash. It kept popping up with an error that said "Connection Error trakt api. suppressing attempt" or something like it multiple times. 

I decided to run that test version to grab a log of it so you can maybe check the difference and the error didn't even pop up this time. I'm guessing since the 4k max has more processing power than my fire tv, it was able to push through the crash the first time. 

Here's the log from my 4k max.
https://paste.kodi.tv/yejutejuje.kodi

Oh and my 4k max is still on kodi 19.3. I was worried about updating it after the issues I had on the tv so I kept it there.

**Comment by jurialmunkey** [comment] 2022-03-17 04:05
> Could this be device specific? I ask b/c I have pretty much the same set up and same shows on my pc and have no issues with 4.6.38.

If you're using the same Trakt account on both devices, then I think you're onto something here. That'd likely point to either an overheating or out of memory issue, which would explain the sudden crash without an error message.

Can you try the new version (v4.6.40~testing) that I just pushed to the testing branch. I've  added an option under expert settings to limit the max number of threads.

Start with 10 threads and see if that works. That will be the slowest but if it works then we know that it is a memory or overheating issue from attempting to run too many threads at once. Then basically you'd keep bumping the threads up to find the sweet spot between performance and stability.

Let me know if limiting the threads works and I'll merge the change into the main branch so you can actually use it without the log being flooded with the testing messages!

**Comment by GodsLikelyMe** [comment] 2022-03-17 04:57
Ok not sure what else you did, but they all worked. 10-50 and 0 (unlimited). Could getting it to work the first time on 10 possibly got it to push through whatever was causing it to hang?

**Comment by jurialmunkey** [comment] 2022-03-17 05:51
> Ok not sure what else you did, but they all worked. 10-50 and 0 (unlimited). Could getting it to work the first time on 10 possibly got it to push through whatever was causing it to hang?

It'd be because the results for each item are cached. So second time through its much faster because its just a database lookup rather than having to download data and process it. Also Next Up is pretty CPU intensive because it needs to sort through a lot of sync data to figure out which episode is next.

So once cached, likely the earlier threads are completing quickly before lots of new thread spawn and you never max them out. To get a fair comparison, when you change the thread limit you'd need to also delete the trakt cache and then restart.

**Comment by jurialmunkey** [comment] 2022-03-17 05:51
Either way though, that is good news! I'll add in the changes to the main branch now.

**Comment by GodsLikelyMe** [comment] 2022-03-17 05:53
You're awesome! Thank you for helping out and putting up with me lol

**Comment by jurialmunkey** [comment] 2022-03-17 06:18
> You're awesome! Thank you for helping out and putting up with me lol

No problem at all! 

I don't have any low powered Android devices so I'm pretty in the dark on that front - so it really helps having someone willing to do tests and do some investigative digging to find out when the issue started happening.

I've added the thread limit update to the main (i.e. matrix) branch now.

**Comment by GodsLikelyMe** [comment] 2022-03-17 07:15
Just installed the main one. Started off with 20 and it took a little bit to load but eventually went smoothly. Will be sticking with that.

Thanks again and if you ever need some testing, just let me know. I'll be more than happy to.

**Closed as completed** 2022-03-17 07:19 UTC
