### ISSUE TITLE
Bug[Next Aired watched/unwatched]

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/plugin.video.themoviedb.helper#350] opened 2020-11-08 15:48 UTC
Next Aired is displaying watched/unwatched icons. Also when unwatched is selected tv show thumbnails are displayed.
I notice this issue before the current update.

watched
![watched](https://user-images.githubusercontent.com/2873112/98469827-cca64280-21d9-11eb-9244-a5733a9d84c5.jpg)

unwatched
![unwatched](https://user-images.githubusercontent.com/2873112/98469838-d760d780-21d9-11eb-88df-94c5971327aa.jpg)

**Comment by jurialmunkey** [comment] 2020-11-08 21:18
Closing duplicate of #351

**Closed by jurialmunkey** 2020-11-08 21:18 UTC
