### ISSUE TITLE
[BUG] Themoviedb helper error

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/plugin.video.themoviedb.helper#1257] opened 2024-10-05 10:50 UTC
### Describe the bug

Hi @jurialmunkey hope you doing well.
“Themoviedb helper error” pops up on the upper right corner whenever I launch Kodi. It says see log for more information below that error, I have uploaded the relevant section from kodi.log (let me know if you need the full log file). I wouldn't mind to see that message as it disappears after few seconds but the main issue is that most of the times it will crash my Kodi, so need help to resolve that. I am using Kodi 22-Alpha 1 (https://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/) in my Shield 2019 device and TMDb Helper v5.2.31 which I believe is the latest from Jurialmunkey Alpha repo.

### Steps To Reproduce

Launch Kodi
Error displays on upper right
Kodi crashes

### Debug log

https://paste.kodi.tv/saquhowesa.kodi

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment] 2024-10-06 08:28
Full log. These are not exception messages generating a notification.

**Comment by onlytanmoy** [comment] 2024-10-06 17:58
> Full log. These are not exception messages generating a notification.

Here you go @jurialmunkey 
[kodi.log](https://github.com/user-attachments/files/17270446/kodi.log)

**Comment by jurialmunkey** [comment] 2024-10-07 04:38
Duplicate of https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/1251

Something to do with Piers using Python 3.12 which is messing with zlib library decompression and/or sqlite3 usage.

**Closed as completed by jurialmunkey** 2024-10-07 04:38 UTC
Labels: bug

**Comment by onlytanmoy** [comment] 2024-10-07 08:59
> Duplicate of #1251
> 
> Something to do with Piers using Python 3.12 which is messing with zlib library decompression and/or sqlite3 usage.

ok, so is the solution to install the latest nightly Libreeelc in my Shield? @jurialmunkey

**Comment by onlytanmoy** [comment] 2024-10-12 15:48
@jurialmunkey can you please point me to the url to download Libreeelc for Shield? google search not helping much :( OR  do I need to install a different version of Python?

**Comment by Nanomani** [comment] 2024-10-12 16:49
@onlytanmoy,

> @jurialmunkey can you please point me to the url to download Libreeelc for Shield? google search not helping much :( OR do I need to install a different version of Python?

1 - Libreelec for shield pro does not exist :)
2 - Kodi v22 for Android (Shield Pro) is here : https://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/
2 - You must make a try with Python embeded 9.11.x version

the last one is : 
[kodi-20240906-4048fa02-master-arm64-v8a.apk](https://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/kodi-20240906-4048fa02-master-arm64-v8a.apk)

**Comment by onlytanmoy** [comment] 2024-10-12 16:53
@Nanomani thank you

**Comment by onlytanmoy** [comment] 2024-11-24 12:29
@Nanomani hope all well...I am currently using the Python embedded 9.11.x version (kodi-20240906-4048fa02-master-arm64-v8a.apk) as you suggested and no issues whatsoever, so many thanks for that.
I tried the latest Kodi v22 nightlies from here https://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/
and instantly got the errors, so reverted to the Python embedded 9.11.x apk and again all good. Just wanted to check that I need to stay with that version only and no possibility of updating to v22 nighlies?

**Comment by Nanomani** [comment] 2024-11-24 13:52
@onlytanmoy 
Feedback is always appreciated. I'm happy for you.

Regarding errors with the latest version v22. I have the same behavior as you with TMDb Helper.
(Shield 2019 Pro, Libreelec 13 x64).

Everything is confusing right now for me. I don't know at what level this needs to be fixed (Kodi, Python, Addon TMDb, Other ...) and if this is discussed between experts?.

A solution will be found in a future, I'm sure. 
For the moment it is not possible to use the latest Nightly Kodi v22 (except with Windows OS) without TMDb Helper error.

Actually Kodi v22 is Pre Alpha1 :)
So wait and see
