### ISSUE TITLE
Players - Default players for episodes gives error when trying to assign a default player

### ISSUE THREAD

**Issue by TechXXX** [jurialmunkey/plugin.video.themoviedb.helper#865] opened 2022-09-17 11:45 UTC
### Describe the bug

Installed a fresh copy of Kodi 19.4 at my brothers house last night (android, shield) and tried to enter the default player (after getting it from URL). It gave an error (upper right corner tmdb error) and wouldn't let me enter the episode player, movie player wasn't a problem. Back at home I tried altering my working version of episode player and I got the same error (but mine is already filled in). Here's the entry in the log:

p.s. I've added my log, I'm using Kodi 20 nightly but like I said I had this problem on my brother's clean 19.4 install too.  

`2022-09-17 13:34:18.555 T:80037    INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2022-09-17 13:34:20.709 T:80037    INFO <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2022-09-17 13:34:24.431 T:80037    INFO <general>: Loading skin file: DialogExtendedProgressBar.xml, load type: LOAD_ON_GUI_INIT
2022-09-17 13:34:24.440 T:82630    INFO <general>: [plugin.video.themoviedb.helper]
                                                   TMDbHelper - 00 Constructing Players...
2022-09-17 13:34:24.468 T:82630   ERROR <general>: GetDirectory - Error getting /Users/kalter/Library/Application Support/Kodi/userdata/addon_data/plugin.video.themoviedb.helper/reconfigured_players/
2022-09-17 13:34:24.468 T:82630   ERROR <general>: GetDirectory - Error getting special://profile/addon_data/plugin.video.themoviedb.helper/reconfigured_players/
2022-09-17 13:34:24.468 T:82630    INFO <general>: [plugin.video.themoviedb.helper]
                                                   TMDbHelper - 33 Retrieving Item Details...
2022-09-17 13:34:24.470 T:82630    INFO <general>: [plugin.video.themoviedb.helper]
                                                   TMDbHelper - 66 Building Player Dialog...
2022-09-17 13:34:24.473 T:82630    INFO <general>: [plugin.video.themoviedb.helper]
                                                   TMDbHelper - Done!
2022-09-17 13:34:24.476 T:82630   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'set_details'
                                                   Traceback (most recent call last):
                                                     File "/Users/kalter/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/script.py", line 7, in <module>
                                                       Script(*sys.argv[1:]).router()
                                                     File "/Users/kalter/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 106, in router
                                                       return self.routing_table[route_taken](**self.params)
                                                     File "/Users/kalter/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 64, in <lambda>
                                                       lambda **kwargs: importmodule('resources.lib.script.method', 'set_defaultplayer')(**kwargs),
                                                     File "/Users/kalter/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/method.py", line 311, in set_defaultplayer
                                                       default_player = Players(tmdb_type).select_player(detailed=True, clear_player=True)
                                                     File "/Users/kalter/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/player/players.py", line 103, in __init__
                                                       self.dialog_players = self._get_players_for_dialog(tmdb_type)
                                                     File "/Users/kalter/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/player/players.py", line 225, in _get_players_for_dialog
                                                       dialog_play = self._get_local_item(tmdb_type)
                                                     File "/Users/kalter/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/player/players.py", line 174, in _get_local_item
                                                       file = self._get_local_movie() if tmdb_type == 'movie' else self._get_local_episode()
                                                     File "/Users/kalter/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/player/players.py", line 211, in _get_local_episode
                                                       self.item = self._set_external_ids(
                                                     File "/Users/kalter/Library/Application Support/Kodi/addons/plugin.video.themoviedb.helper/resources/lib/player/players.py", line 120, in _set_external_ids
                                                       details.set_details(details=self.details_ext_ids, reverse=True)
                                                   AttributeError: 'NoneType' object has no attribute 'set_details'
                                                   -->End of Python script error report<--
                                                   
`

### Steps To Reproduce

Settings - Players - Default Players for episodes - Try to alter

### Debug log

https://paste.kodi.tv/oqadobeqog.kodi

### Screenshots and Additional Info

<img width="1728" alt="Screenshot 2022-09-17 at 13 43 04" src="https://user-images.githubusercontent.com/10571873/190854872-2fdc1399-836a-4196-875d-869e96d59d41.png">

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [X] I have uploaded my debug log.

**Comment by jurialmunkey** [comment] 2022-09-17 12:42
Duplicate of #864 
Already fixed. Please make sure you are using most recent version.

**Closed as completed by jurialmunkey** 2022-09-17 12:42 UTC
Labels: bug

**Comment by TechXXX** [comment] 2022-09-17 12:49
Thanks, next time I'll look through closed issues first ;)
