### ISSUE TITLE
[Enhancement] Discover Rolling Release Date

### ISSUE THREAD

**Issue by Demonseeed** [jurialmunkey/plugin.video.themoviedb.helper#86] opened 2020-02-11 01:01 UTC
Hello jurialmonkey!

So I was really playing around with the Discover section of the addon and I thought of a few enhancements that of as always may or may not be possible and one thing I think is a bug. 

Enhancements:
1. A rolling release date. Now I know the API doesn’t allow you to input a rolling date of some sort, but the addon might be able to take an input and then convert it over to a format for the release date field. 

For example: The field could ask for how long you want the rolling period to be (let’s say options between 1-6 months). You choose 3 months, and then the addon does the math by subtracting 3 months from today’s date and uses that to input the date in the release date field. Every x period of time, the list updates the field without input from the user. 

Use case would be an always updated list of “Latest Releases” that doesn’t rely on a Trakt list someone has to update, and doesn’t rely on the user to constantly have to change the date themselves. Could also have other factors like release_type = 4|5 for latest releases that aren’t in theaters, or latest horror movies. 

2. Random sorting. I know this one is also not an option in the API, but would it be possible for the addon to retrieve the list of movies/shows, then randomize the list itself before displaying it? 

3. No matter what list you choose, it always bring back 10 results. Would it be possible to bring all, but paginize it?

Bug:
1. I don’t think the release_type rule works. I put in 4 (which should be for Digital) with a rule for primary release year of 2020, and it still pulls movies from theaters. I also made sure MATCH is set to all. The example movie I get in theaters still is Birds of Prey (among others). It pulls the same results no matter what I put in for release_type, even if I include one that isn’t possible (like 38295 as the release type). 

When attempting it on the API’s website for Discover, and input the same queries, it works as intended. 

Sorry for the huge post lmao.

**Comment by jurialmunkey** [comment] 2020-02-11 03:03
1. Rolling release date sounds like a good idea. The actual translation of the date/time shouldn't be too difficult (would just do it on container update - e.g. plugin translates date of "two weeks ago from today" to be the correct datetime object when the container is opened or widget is refreshed). Main hurdle is how to handle inputting and saving the rule but it shouldn't be too difficult.

2/3. Plugin should return 20 results (TMDb default) - I don't do any limiting, maybe your widget has a limit of 10 items set? And that feeds into the issue with randomising - it just isn't possible to pull more than 20 items without multiple requests, and making multiple requests for multiple pages and randomising the result isn't really feasible. You can randomise the results in the page using standard kodi sort methods.

4. release_type should now be fixed. There was a typo in the param. Can you test latest and confirm.

**Comment by Demonseeed** [comment] 2020-02-11 03:14
Have to make dinner, will add some more input about the the enhancements when I am done, but I did test the new build right quick. 

It now does something a bit weird. 

I set the release date to 2020, then after set the release type to 4 (for Digital) and hit okay. Once that happens, a new window pops up with a list of movies that meet both criteria, and I can’t get out of that window except by hitting back or selecting a movie. 

Hitting back deletes the rule. Choosing a movie adds the name of the movie as the input for the rule (release type). I can try to record a video.

**Comment by jurialmunkey** [comment] 2020-02-11 04:14
Can you test latest? I think I know what the problem is and it should hopefully be fixed (I don't have access to a computer with Kodi setup right at the moment but I'm pretty sure this should fix things).

For rolling release, the actual inputting isn't the problem (I think that will just be a numeric value of number of days +/- from today) - I'm more thinking in terms of coding it and how the plugin url should store the values.

**Comment by Demonseeed** [comment] 2020-02-11 04:33
That did the trick, it works now. Thank you my friend!

One more thing about that actually that I just realized. The API accepts multiple options for release type by using a ,(and) or a |(or). 

However the addon only allows numbers, so special characters like that are not able to be inputted in, nor can another copy of the rule be added alongside the first. 

Though I’m sure once the list is set as a widget, it could be manually edited so it’s not a huge factor.

**Comment by jurialmunkey** [comment] 2020-02-11 04:45
Can you not click and add another value?

**Comment by Demonseeed** [comment] 2020-02-11 04:51
No. Let’s say I add 4 for digital to release type. 

Once I hit add rule again and scroll down to release type, it already lists a value of 3. If I click on it and change it to 4 for physical, it changes the already existing rule instead of adding another one for 4.

**Comment by jurialmunkey** [comment] 2020-02-11 05:13
Ah okay - I'll have a look at allowing multiple values once I'm back home.

**Comment by Demonseeed** [comment] 2020-02-11 05:21
Alright sounds good my man!

Also quick question - when Match is set to ANY, does that mean if I set a rule for release date = 2020, release type = 3, and genre = horror, will it pull all results that match any of these three categories?

**Comment by jurialmunkey** [comment] 2020-02-11 07:32
No, with match ANY, movies must match at least one value from EACH rule. For instance if I have:
Genre = Comedy, Adventure
With Cast = Arnold Schwarzenegger, Danny Devito
Match ANY

I'll get movies such as Kindergarten Cop (Arnold + Comedy), Matilda (Devito + Comedy) and Conan (Arnold + Adventure) but I won't get The Terminator because it isn't a comedy or adventure movie.


Good point about matching ALL though. I think release matching probably needs to always be ANY.

**Comment by Demonseeed** [comment] 2020-02-11 07:41
Ahhhhh that makes a lot more sense. 

I may have had the premise wrong but the idea was right 😂😂 thanks for letting me know how that worked.

**Comment by jurialmunkey** [comment] 2020-02-12 02:58
@Demonseeed - Please test latest. You should now get a dialog select box to choose release types from. No more checking what the numbers are and you can select multiples. The separator for these is hardcoded to 'OR' (i.e. match ANY) regardless of what your match settings are.

**Comment by Demonseeed** [comment] 2020-02-12 03:47
Just tested, that did the trick! Works like a charm.

**Comment by jurialmunkey** [comment] 2020-02-12 03:54
@Demonseeed - Excellent. Also can you test commit I just pushed.

Release date fields will now take relative values in the format `T-X` or `T+X` where X is the number of days from today. For instance, `T-14` is a fortnight ago and `T+7` is next week.

Accepted for release_date, primary_release_date, air_date, first_air_date.

**Comment by Demonseeed** [comment] 2020-02-12 04:30
So I tested it and I’m pretty sure it works, but I want to verify it’s behavior. 

I think the issue is both primary_release_date and release_date are all >,< and =. 

So when I put T-30 for testing, I assumed it would grab all movies in a 1 day rolling period. 

If I put it in either release_date (primary or not) with > and =, it grabs all movies all movies starting from T-30 and onwards. Opposite for < and =, all movies T-30 and older. 

I assume this is intended behavior, only other thing I can think of how it might be intended behavior (and might not be a bad idea either) is if T-30 grabbed all movies between today and 30 days ago (nothing more or less).

**Comment by jurialmunkey** [comment] 2020-02-12 04:50
Yes that's how those fields work on TMDb.

To get all movies released exactly 30 days ago you would need to do:
```
primary_release_date => T-30
primary_release_date =< T-29
```

Also, you can use T-0 for today, so you can get all movies released in last 30 days with:
```
primary_release_date => T-30
primary_release_date =< T-0
```

**Comment by Demonseeed** [comment] 2020-02-12 04:54
Youuuuu right, I straight up forgot I could do that. 😂

So as I go on my quest to eliminate my dependency on trakt lists as widgets and replace them with this awesome feature (as much as possible anyway), I’m probably going to have more potential enhancements.

Would you like me to keep them contained on this issue or just open up more as I come through them?

**Comment by jurialmunkey** [comment] 2020-02-12 05:04
> Would you like me to keep them contained on this issue or just open up more as I come through them?

Each feature as a separate issue makes things easier for me to keep track of.

Also, keep 'em coming! 😁

**Comment by Demonseeed** [comment] 2020-02-12 05:15
Sounds good, will do!

I’m glad you are okay with that because I have already thought of two more since we I have been testing this. 😅

One of them I’ll add to this one in a bit (watching a movie with the wife) because it’s about release type again. The others I’ll add as their own.

**Comment by Demonseeed** [comment] 2020-02-12 06:52
So while testing out the release_type briefly, I did run into another caveat. 

With everything set to OR, if I select Digital and Physical - it pulls things that have a physical or digital release. As I went through the results, I noticed it was also pulling things are direct-to-video Physical/Digital media (no theatrical release). 

While digital isn’t so bad since Netflix has a lot of digital only content, straight to DVD content has a few diamonds but for the most part are non-desirables. 

Then I came to the idea that the solution is being able to tell the query (Physical or Digital) and Theatrical release. This way it pulls things that were once in theaters but since have been released on physical/digital. 

I did try creating it as a widget with physical/digital selected, and manually added `&amp;with_release_type=3` but it didn’t seem to work.

**Comment by jurialmunkey** [comment] 2020-02-12 07:48
You have to send all the values as one param, you can't have two `&with_release_type=` params because the second one will just overwrite the values in the first.

This type of thing really needs to be added manually. TMDb API allows for treats comma separated values as AND and pipe `|` separated values as OR. However, you need to url encode as these are reserved characters - comma url is `%2C` and pipe url is `%7C`

What theatrical releases with either digital or physical release can be done with:
`&with_release_type=4,3|5,3` which is url encoded to:
`&amp;with_release_type=4%2C3%7C5%2C3`

**Comment by Demonseeed** [comment] 2020-02-12 07:52
Sounds good, I will definitely check it out tomorrow. Manual is perfectly fine to me, as I have many manually typed widgets anyway. Thanks again!

Though I do say, if testing this does work - next time you update the Discover wiki, can you add this as an example?

**Comment by Demonseeed** [comment] 2020-02-13 05:16
To update - it doesn’t work. However, I don’t think it works at the API level either. 

I went to the API’s documentation site where you can test out the API:
https://developers.themoviedb.org/3/discover/movie-discover

Inputting Theatrical + Digital (or physical) doesn’t seem to work at all, so I made a forum post about it.

**Comment by jurialmunkey** [comment] 2020-02-13 07:41
Yeah, I can confirm that comma doesn't appear to be working on their API. It looks like it is being treated as a pipe.

I looked for movies `with_release_type=3,5` and the new Harley Quinn movie was showing in the results despite it only having a `3` release type currently (no `5` release type since it is only just out now).

**Comment by Demonseeed** [comment] 2020-02-13 14:40
Sweet! I appreciate that confirmation as I’m not as experienced with this API. I’ll update this post once they get back to me on their forum. 

On a side note I also made a request for the ability to essentially query “Find me all movies that were released by Netflix (or Hulu, Amazon, etc).” I’ll make another issue when that’s been implemented as they seemed to like the idea.

**Comment by jurialmunkey** [comment] 2020-02-13 20:56
> On a side note I also made a request for the ability to essentially query “Find me all movies that were released by Netflix (or Hulu, Amazon, etc).” I’ll make another issue when that’s been implemented as they seemed to like the idea.

Awesome! Yeah that would be an amazing feature to have, especially if it works with the `region` param (AU Netflix is very different to US Netflix in terms of what is available). Would be really useful for integration with Netflix/Amazon etc. plugins.

**Comment by Demonseeed** [comment] 2020-02-13 21:05
So turns out they had the same idea we did - release type is hard coded to OR. They are working implementing AND to it. 

Does AU Netflix have Netflix originals that are only released to AU Netflix (or vice versa)? He did mention it wouldn’t be designed to be able to pull currently accessible data, just stuff that was released by the company at one point. 

But if they do, it sounds like you could use it conjunction with region to essentially do that anyway (to some degree).

**Comment by jurialmunkey** [comment] 2020-02-13 22:17
All the Netflix originals are available for all regions I'm pretty sure - but you could get Netflix originals by checking for studio.

I mean the rest of their (non original) catalogue differs by region but it sounds like that might not be possible to check for

**Comment by Demonseeed** [comment] 2020-02-13 22:23
> All the Netflix originals are available for all regions I'm pretty sure - but you could get Netflix originals by checking for studio/company

I tried this but sadly it didn’t seem to work for movies (it only pulls 1 result). 😓 The only way to my knowledge was pulling by network, but it only exists for TV shows. 

> I mean the rest of their (non original) catalogue differs by region but it sounds like that might not be possible to check for

Ahh I gotchu, I do not think that is possible as they mentioned in a different post that Netflix closed their API for this.

**Comment by Demonseeed** [comment] 2020-02-15 23:41
Update:
It would not work to try to mix AND/OR on release_type as the API doesn’t support this (for anything actually). It is something that is in their backlog to support. Here’s the ticket:
https://trello.com/c/mgWoRG5K/17-add-advanced-discover-filters

Here’s the ticket for them implementing the ability to query movies made by whatever network they come from:
https://trello.com/c/ilQHnHHW/195-add-a-provider-type-field-to-release-dates

If either of those are things you would be interested in, you can vote for them on the ticket to help prioritize what they work on. I personally voted for both lmao.

**Comment by jurialmunkey** [comment] 2020-02-16 00:57
I had a feeling that would be the case re mixing operator types. Will definitely vote on both those (once I dig up my trello credentials - haven't logged into trello in a long time!).

Hopefully at least they'll be able to implement the AND operator for release types, as that would be very useful. A list with rolling release date of last month, with digital releases that were also in theatres, for my region, and sorted by popularity would get a lot of use out of me as there's a lot of stuff I miss at the cinema and then it sort of falls of my radar because I forgot to watchlist it.

**Comment by Demonseeed** [comment] 2020-02-16 01:22
Same! That’s exactly the reason I want it as I tend to miss movies I really wanted to see and then forgot about them for like 3-5 years. 😂

I’m hoping that after these changes, we can effectively recreate the “Latest Releases” list by Gilad & Alex, but actually customizable. I’m super excited!

**Closed** 2020-02-19 12:44 UTC
