### ISSUE TITLE
Change the default sort order of episodes 

### ISSUE THREAD

**Issue by ananias47** [jurialmunkey/plugin.video.themoviedb.helper#237] opened 2020-05-24 15:58 UTC
Hi my friend again sorry if i ask you so many questions

Can i make the default sort order of episodes to be 'episodes' so as to show the number of episode without doing it every time??

Thnx again

**Comment by jurialmunkey** [comment] 2020-05-25 10:45
The problem is that many of the episode lists don't make sense to sort that way.

For instance, you wouldn't want Next Up Episodes or Recently Watched or Next Aired Episodes to be sorted by episode.

**Comment by ananias47** [comment] 2020-05-25 19:20
yes my friend i understand what you mean

maybe if you force view types on each diferent section i dont know

**Comment by jurialmunkey** [comment] 2020-10-18 03:49
Resolved in upcoming v4 release (currently available in "refactor" branch).

**Closed by jurialmunkey** 2020-10-18 03:49 UTC
