### ISSUE TITLE
TMDb Helper add-on does Not auto update

### ISSUE THREAD

**Issue by onlytanmoy** [jurialmunkey/plugin.video.themoviedb.helper#522] opened 2021-06-28 14:13 UTC
Hiya, Kodi does not notify for available updates for TMDb Helper addon, can you please look into this?

Looks like I am not alone, some other users also reported it, example below :)

https://www.reddit.com/r/Addons4Kodi/comments/o93cen/themoviedb_helper_does_not_auto_update/?utm_source=ifttt

**Comment by drinfernoo** [comment] 2021-06-28 14:37
As of Kodi Matrix, you'll need to have the "Update official add-ons from" setting set to "Any Repositories" for this to work.

**Comment by onlytanmoy** [comment] 2021-06-28 14:41
:) that's already in place good doc, still no notification shown once TMDb updates are available.

**Comment by drinfernoo** [comment] 2021-06-28 17:06
Do you also have "Show notifications" turned on?

**Comment by drinfernoo** [comment] 2021-06-28 17:06
And do you have the latest version of the repo installed? https://www.reddit.com/r/Addons4Kodi/comments/o93cen/comment/h3b7wgi/

**Comment by onlytanmoy** [comment] 2021-06-28 17:43
Yes doc, I got Jurialmunkey Alpha Repo v2.2 installed and of course show notifications is ON under Updates (it is set as Notify, but don't install updates)

**Comment by drinfernoo** [comment] 2021-06-28 18:33
@onlytanmoy What version of TMDbHelper do you have installed?

**Comment by onlytanmoy** [comment] 2021-06-28 18:44
4.3.13

**Comment by jurialmunkey** [comment] 2021-06-29 01:15
Press info on TMDbH in addon browser. Select "versions" button and choose the repo version. Kodi should now track the repo.

**Comment by kolekan** [comment] 2021-06-29 05:52
> Press info on TMDbH in addon browser. Select "versions" button and choose the repo version. Kodi should now track the repo.

I have already done this for every single update since 4.3.7 version .  Kodi always track the official repo for any addon that is in kodi addons repo.

**Comment by jurialmunkey** [comment] 2021-06-29 08:36
> I have already done this for every single update since 4.3.7 version . Kodi always track the official repo for any addon that is in kodi addons repo.

You can report Kodi bugs here:
https://github.com/xbmc/xbmc/issues

**Comment by jurialmunkey** [comment] 2021-06-30 03:05
Closing this as it is a Kodi or user setup issue and not a bug with TMDbH or my repo. If you're still having issues with tracking my repo, please report it to the xbmc github as that's the only way it is going to get fixed.

I'll push an official repo update soon.

**Closed as completed by jurialmunkey** 2021-06-30 03:05 UTC
