### ISSUE TITLE
[Feture Request] Ability to add Custome view and view ids like seren. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/plugin.video.themoviedb.helper#543] opened 2021-07-27 13:51 UTC
Hi, I just wanna say that i love this addon but i miss openmeta and openinfo and i wish they could be revived in the future but i wanted to ask if you could add Custom view and view ids to your addon. Your addon is really great and i wanna use it for more skins and more builds but i cannot use it due to limitations like icon limitations and view limitations. Again, really love your addon and hope to see costume view ids which would be a big help for my builds. Thank you for making this addon and i hope to use it in the future. 

![image](https://user-images.githubusercontent.com/62456796/127164610-d5c2f4c0-8978-48c1-bd5a-547802fcbe2b.png)
![image](https://user-images.githubusercontent.com/62456796/127164638-85c55f2a-562c-497b-8ce8-de3d7d9df2b0.png)

**Comment by drinfernoo** [comment] 2021-07-27 13:59
You just change the view in your skin.

**Comment by Goldenfreddy0703** [comment] 2021-07-27 17:53
> You just change the view in your skin.

Actually there is view option for the skin I'm using where you can change it but I have other addons that require some different views that I can work with and the skin I'm using can only change the video addons view, nothing else sadly. This reason why I'm asking for this future request is so that I could use this addon with different skins like emby, eminence, osmc, ect.

**Comment by jmh2002** [comment] 2021-07-27 22:53
Yes, I think this would be a useful feature. It was also requested here back in February: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/433

Kodi itself doesn't seem to handle the Views of addons that use online databases very well, especially ones with so many layers of directories like TMDBH.

It seems necessary to set the View for every single directory in TMDBH, not just what media type the directory displays, ie: Movies, TV Shows, or Episodes. And then when going to the next page in that directory the View is forgotten and needs to be set again - and some directories have 10 or 20 or more pages... 

Even with something like Trakt In Progress TV Shows, if a new TV Show enters the list, it's necessary to set the View when clicking through to the Episodes of that new Show before it is remembered and saved. 

And with multiple Kodi installations throughout the house it's all somewhat frustrating to keep the View setup correct.

Worse still is going into TMDBH itself and browsing - every single directory needs it's View to be set manually - and there are A LOT of directories. I didn't count them all but there must be at least 50, plus whatever personal lists from Trakt, etc. 

Multiplying the number of directories, by multiple pages in each directory, and by multiple Kodi installations at home, and it's literally hundreds if not thousands of pages that each need their View to be manually...

Additonally, depending on the addon, the skin, etc, there sometimes seems to be some conflict regarding what the actual Media type is, and therefore what View should be set.

For example, there are some addons that allow View types to be set, and this seems to function across Kodi, not just in that particular addon. But in this case TMDBH > Trakt In Progress TV Shows list seems to be detected as an Episode list, not a TV Show list, thereby applying the incorrect View type.

So it would be a really nice convenience if this feature could be incorporated correctly into TMDBH itself please. 

THANKS for considering it :)

**Comment by Goldenfreddy0703** [comment] 2021-07-28 00:14
I honestly am happy to hear that people want this feature. I really hope @jurialmunkey can consider this feature into his addon cause it would really help all of us out. I really love tmdb helper and i hope to see it with some costume views in the feature. Thank you @jmh2002 for supporting this issue with me.

**Comment by jurialmunkey** [comment] 2021-07-28 02:20
Closing this issue as duplicate of #433 
Please keep discussion in the thread that already exists.

FYI if an issue remains open then it means that I will work on it eventually. If comments are kept in one thread then it is much easier for me to keep tabs on the discussion.

**Closed as completed by jurialmunkey** 2021-07-28 02:20 UTC
