### ISSUE TITLE
Clearlogo not working (local artwork) on OSD

### ISSUE THREAD

**Issue by simtaj** [jurialmunkey/plugin.video.themoviedb.helper#1021] opened 2023-03-06 20:16 UTC
### Describe the bug

Using PlexKodiConnect with direct paths and local artwork saved in movie folder. 
When adding movie in Kodi I have only poster and fanart if you check artwork trough manage. If you go trough information-manage and choose refresh then all local artwork shows and works on OSD. But after that all refreshed movies disappears from choosed item menu (Videos,library://video/Plex-1/1_all/,return) and coresponded widgets. 
They stays only in menu item (Videos,library://video/movies/titles.xml/,return)

### Steps To Reproduce

1. Plex adds new movie with local artwork
2. on added movie go to information, manage, artwork (there is no extra artwork added from local folder)

### Checklist

- [X] I have searched the issues and this bug has not been reported.
- [X] I have updated TMDbHelper to the most recent version.
- [X] I have described the bug and included steps to reproduce the issue
- [ ] I have uploaded my debug log.

**Comment by jurialmunkey** [comment] 2023-03-06 20:30
This sounds like a plex kodi connect problem. Tmdbhelper doesn't control your library or plex kodi connect.

You would need to speak with the PKC author about how to add extra artwork to your library without affecting the plex paths. 

If the item in the library has artwork then tmdbhelper will use it. Otherwise it needs to do a lookup which depends on the item having correct metadata.

**Comment by simtaj** [comment] 2023-03-06 20:33
Thank you for your help. But if tmdbhelper doesn’t see my local artwork, why it doesn’t lookup for them ?

**Comment by simtaj** [comment] 2023-03-06 21:19
I tried now trough Kodi library item menu (Videos,library://video/movies/titles.xml/,return) on one movie trough contex menu, choosed TMDbHelper Options-Manage artwork-refresh all artwork. TMDb helper said that it find artwork for this movie (clearart, banner, clearlogo, discart …) Then I check this movie on information page-manage-artwork and movie still don’t have this extra artwork that TMDbhelper said it found it. So why is that? I assumed that this would have to work if tmdbhelper lookup for extra artwork..Thank you again. I really like this skin and I am very sad is not working for me…

**Comment by jurialmunkey** [comment] 2023-03-07 00:06
"Info - Manage Art" is the artwork in your library. If you have artwork set for clearlogo there then TMDbhelper will use it

"tmdbhelper option - manage" is the artwork tmdbhelper has looked up online. This artwork is only used if the local item doesn't have artwork.

If your local item sets a clearlogo that doesn't exist then tmdbhelper will not have art. It only cares about whether a filename is listed, it doesn't read the artwork to check it exists.

**Comment by simtaj** [comment] 2023-03-07 05:52
Ok, so if I understand well. TMDbhelper doesn’t understand my local clearlogo and think I have it, because of the name filename (movie-trailer). So the only option is to delete all my local artwork or change skin ?

I contacted the author of PKC and he said, that with other skin local artwork works. People used it for example with "Estuary MOD v2" and it working for them.

**Comment by simtaj** [comment] 2023-03-07 07:13
Now I deleted all extra artwork in folder for one my movie. Then I went on tmbdhelper option - manage and refresh all artwork. Again tmdbhelper said it found artwork, but then when I check them I still don’t have it…?

**Comment by jurialmunkey** [comment] 2023-03-07 23:12
Refreshing artwork in tmdbhelper is not going to do anything. You need to add the art to pkc

**Comment by simtaj** [comment] 2023-03-07 23:28
So If I don’t have any local artwork in my folders, TMDb won’t lookup by himself for extra artwork never ?
This worked for me on TitanMod skin, witch I changed for AH2.

**Comment by jurialmunkey** [comment] 2023-03-08 01:48
> So If I don’t have any local artwork in my folders, TMDb won’t lookup by himself for extra artwork never ? This worked for me on TitanMod skin, witch I changed for AH2.

That's a different issue... Your issue you posted said that local artwork was not working. If you don't set local artwork then local artwork won't work.

As to why TMDbHelper is not finding the item to lookup online information, that could be any number of reasons from incorrect metadata or IDs set in PKC to the language of the item not matching the language set in TMDbHelper, or the title not matching what is on TMDb website.

**Comment by simtaj** [comment] 2023-03-08 07:20
Sorry If I didn7t explained enough, I will try my best It is diffucult only with writing.

I tried to find new way for extra artwork, because you said that with PKC local artwork won’t work.  PKC has no setting to enable that I have local artwork. It just passes movie folder with smb paths to KODI. (I can see all my smb shares on KODI). So I can’t enable anywhere option for local artwork.  But poster and fanart is visible from my local artwork. Problem is only with extra artwork. PKC then has option to lookup on web extra artwork (with fanart.tv and caches it to KODI), this I disable it because I had allready local artwork in folder with movie. 
If I enable this in PKC, PKC find every extra artwork on web like other scrapers with no problem, so this is working and is showing every artwork if I go on movie information-manage-artwork.

Beacuse I wanted to try If TMDb helper can lookup this extra artwork for me, when I have scraping with PKC disabled.  I deleted extra artwork for few of my movies in my local folder and leave only poster and fanart in folder with movie, because this two TMDbhelper/skin use it. 
After that I went to this movie (with deleted extra artwork) and tried to refresh artwok from contex menu with TMDbhelper. So I assumed If I don’t have any local artwork TMDb will find it. It show windows and say that it find extra artwork (clearlogo, clearart, discart…) for movie with movie ID ( so it finds it). But after that if I check again via movie on information page-manage, movie still doesn’t have extra artwork, like it wasn’t writed in KODI cache. So there is really no difference if I have artwork in folder with movie or if delete it and don’t have it. TMDbhelper acts the same no artwork cachin.

Movie name and NFO, IDs are correct, because other scrapers finds with no problem, even TMDbhelper says it find it and I can see that it finds because I can choose diffrent posters from context menu when it finds it. It just not write anything to cache and it is not showing it movie info-manage-artwork. It looks like it finds it and not set it. I hope you unerstand what I mean. So I assumed with local artwork is the same, TMDbhelper see it, just don’t set it (or write it to cache). 

If i go on movie trough info-manage-artwork and manual choose artwork clearlogo or any other (which shows that is empty), I click clearlogo, then it opens my local artwork and I can choose it and It is writen to cache. But I have to do it manual for every single movie and this is too much work.

This all I can solve with just letting PKC to lookup for all artwork on fanart.tv, but I rather use my local artwork If possible.


Everything I can solve with just letting PKC

**Comment by simtaj** [comment] 2023-03-08 07:34
![IMG_8389](https://user-images.githubusercontent.com/127146576/223649828-84f03439-0357-4ea3-882e-464a331f2dd8.jpg)
![IMG_8390](https://user-images.githubusercontent.com/127146576/223649865-4eda5264-f804-412d-b04c-528cece7ace2.jpg)
![IMG_8391](https://user-images.githubusercontent.com/127146576/223649881-0bc9acd9-b3bd-4d8e-a434-0b92dd8ce518.jpg)
![IMG_8392](https://user-images.githubusercontent.com/127146576/223649904-68e03d50-cc50-47c3-b4f5-416161edc961.jpg)
![IMG_8393](https://user-images.githubusercontent.com/127146576/223649930-c8371772-0ad5-4bb3-b0d6-c59d31bda892.jpg)
![IMG_8394](https://user-images.githubusercontent.com/127146576/223649941-2eb5ea4b-8b01-4719-9c58-33362fae033c.jpg)
![IMG_8395](https://user-images.githubusercontent.com/127146576/223649967-bb5a7534-f0e9-4a40-9b7f-cdc5e4b8a3d2.jpg)
![IMG_8396](https://user-images.githubusercontent.com/127146576/223650000-b26415b5-34ce-4264-a7fd-5b6add2fc0f6.jpg)

**Comment by DROIDshield** [comment] 2023-03-08 07:47
Where did you get you icon's at the bottom of the screen, mine doesn't look like those and also how did you move the number of episodes in the circle from the bottom of the poster to inside the top left?

**Comment by jurialmunkey** [comment] 2023-03-08 08:13
@DROIDshield 

> Where did you get you icon's at the bottom of the screen, mine doesn't look like those

Local items have codec information. Skin automatically displays codec information if available. If there's no codec information then it shows providers instead.

> ... and also how did you move the number of episodes in the circle from the bottom of the poster to inside the top left?
Skin Settings > Details > Indicators > Ratings

**Comment by jurialmunkey** [comment] 2023-03-08 08:29
@simtaj - Thanks for this info.

Refreshing TMDbHelper details will not do anything to refresh the service monitor. The refresh only works for items inside TMDbHelper. From your screenshots I can see TMDbHelper details like genre, budget, and ratings labels so I believe it is looking up the item correctly -- it is just a matter of what clearlogo it is trying to use.

There's a few possible reasons here:

1. TMDbHelper can't read your SMB shares where the local artwork is located. Because there is a clearlogo listed then it doesn't use an online lookup but it also can't read the clearlogo on disk and so the skin falls back to text.
2. When TMDbHelper cached the item it was when you had extra art set in PKC and or the library. You've since removed the extra artwork but TMDbHelper is still trying to lookup the artwork based upon what it has cached

A debug log will probably tell us if the problem is SMB shares.

You can test if there's a cache issue by closing kodi and then deleting the following cache files:
In `kodi/userdata/addon_data/plugin.video.themoviedb.helper/database_v6` delete:
`ItemBuilder.db`
`QuickService.db`

Then restart Kodi

I have a feeling, however, that the issue is probably an SMB access issue and we'll only know that with a debug log.

**Comment by jurialmunkey** [comment] 2023-03-08 08:33
@simtaj 

>Problem is only with extra artwork. PKC then has option to lookup on web extra artwork (with fanart.tv and caches it to KODI), this I disable it because I had already local artwork in folder with movie.

Also note that you still need to **add** the local artwork to your library. Kodi won't magically add it for you simply because you put it in a folder -- you need to add it to the library either manually in manage artwork or by using local information scraper.

**Comment by DROIDshield** [comment] 2023-03-08 15:58
@jurialmunkey thanks for the info above.

**Comment by simtaj** [comment] 2023-03-08 16:47
@jurialmunkey , thank you for your reply

>Also note that you still need to add the local artwork to your library. Kodi won't magically add it for you simply because you put it in a folder -- you need to add it to the library either manually in manage artwork, refresh the individual local information, or using a tool to refresh your whole library.



I think this is the main problem. There's nowhere I can add or mark that KODI knows that I have local artwork. 
I can check (click) every single artwork item in info/manage artwork and then it accept it and show it. But is too many work fore every single movie. 
But I cannot use refresh artwork in info/manage artwork because the movie in PKC library after that disappears. With refresh Kodi not only refreshes artwork, but obviously changes path to Kodi library instead to leave it in PKC library.

Am I thinking right ?

**Comment by simtaj** [comment] 2023-03-09 06:34
Thank you for all your help. 
I will use for now PKC online lookup and manualy add from local only if it mismatch any of them.

Will try to get in contact with PKC author, to ask for enhancement.
Thank you again for your time.

**Closed** 2023-03-09 07:10 UTC
Labels: bug
