### ISSUE TITLE
In-Progress issues (4.5.0)

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#626] opened 2022-01-16 22:14 UTC
Hi. Thought I should start a new thread having previously commented on a closed thread (sorry🙏). In-progress Movies widget doesn’t seem to clear a watched movie. Had one watched film remain in list for 24hrs but did eventually disappear on reboot after a system crash. I can hide watched if they’re not meant to disappear, but would be good to know if this is expected behaviour. 

Regarding in-progress episodes widget, an unfinished local episode played via tmdb helper-trakt-my tv shows, shows up in the in-progress episodes widget but only plays from the start. It does, however, pick up from where it left off via tmdb helper-trakt-my tv shows. Unfinished episodes from seren resume properly via tmdb helper’s in-progress episodes widget. 

Hope this is useful feedback.

**Comment by jurialmunkey** [comment] 2022-01-16 23:43
The in-progress movies and episodes lists retrieve the `sync/playback/{movie|show}` list from Trakt and display any item with a `paused_at` value between 5% to 95% (i.e. so if you stopped watching very early or only in the credits then those won't be included). 

The show/hide watched shouldn't have any relevance _as long as_ the service you are using to scrobble this data to Trakt is also updating the progress status (since a watched item ends up with 100% progress and gets removed from the sync data).

You can confirm this by going to:
`TMDbHelper Settings > Expert > Log output of Trakt request` and inputting `sync/playback/movies`. 

That will generate a log file:
`.kodi/userdata/addon_data/plugin.video.themoviedb.helper/log_request/trakt_syncplaybackmovies.json`

You can open that log in a text editor to see what data Trakt is returning. If the items are showing there with a paused_at value then the service you are using to scrobble that data to Trakt is not working correctly.

If the items are _not_ showing in that list then please let me know as that indicates some issue with the Trakt activity cache not updating correctly instead (so you're getting old cached data when the item was still there).

> Regarding in-progress episodes widget, an unfinished local episode played via tmdb helper-trakt-my tv shows, shows up in the in-progress episodes widget but only plays from the start. It does, however, pick up from where it left off via tmdb helper-trakt-my tv shows. Unfinished episodes from seren resume properly via tmdb helper’s in-progress episodes widget.

This is difficult due to the way Kodi stores in-progress data on a per item basis rather than globally. It wasn't possible to update the progress status of listitems manually in Leia (only watched status), so the progress would only keep for the specific place you played the item from.

New functions were added in Matrix to allow plugins this ability to override the progress value stored by Kodi. I was previously trying to maintain backwards compatibility with Leia, so that's why the option isn't there currently -- but now that I've switched to Matrix only development, I will be introducing it soon.

It's still tricky for 3rd party plugins that don't use setResolvedURL because the progress isn't passed through and they manage it themselves -- but it will at least fix progress for local playing files or via setResolvedURL plugins like Netflix. I'll keep you updated when I add the feature.

**Comment by ghost** [comment] 2022-01-17 00:55
Thanks man. Great news about roadmap for in-progress local files! 

Ok, so I did this twice with same outcome. Streamed a movie and stopped it half way through. The .json file produced shows correct paused_at value, and resumes perfectly…forwarded to end and let credits play out for the last minute or so. The response to entering sync/playback/movies into log output of trakt request is:

sync/playback/movies
No Response!

The movies have disappeared from Seren’s Finish Watching widget but remain in tmdb helper’s in progress movies. 

Happy to help with further testing if needed, but if you can’t reproduce the issue on your end, and this looks like an isolated issue, don’t worry about it. Cheers.

**Comment by jurialmunkey** [comment] 2022-01-17 07:27
Okay, if they're getting removed from the playback sync then I'm assuming that when you watch something 100% Trakt is only updating the `watched_at` activity timestamp and not the `paused_at` activity too.

Trakt really should update both activity values since watching something also changes its paused_at status. But no big deal, I can just check if any of the activity timestamps changed rather than specifically only paused_at.

Can you test 4.5.1 and see if that works for you?

EDIT: Actually, please test 4.5.2 as that also adds the ability to retrieve resume points from Trakt (option to enable it in Accounts section of TMDbHelper settings).

**Comment by ghost** [comment] 2022-01-17 10:28
Enabled retrieve resume points in 4.5.2 and tested. Still get No Response! From log output of trakt requests and movie remains in the in-progress movies widget when watched. A couple of things have changed though:

A watched movie now retains its in-progress status (where I stopped it half way through before resuming and playing to the end) rather than being marked as watched which was happening previously, but has disappeared from Finish Watching widget. However, it is removed from in-progress movies when another in-progress movie is added, which is good enough for me.

I’m refreshing widgets a couple of times to test, but doing all this within 5 minutes or so after watching, which may be too soon to conclude anything?

**Comment by jurialmunkey** [comment] 2022-01-17 11:47
How many movies do you have in-progress? You should only get "No response!" if you don't have any (in which case the widget should be entirely empty). 

Make sure that you're logging the _Trakt_ output not _TMDb_ (there's two different log options). And make sure that you're logging the correct path `sync/playback/movies`

You could compare the output of `sync/last_activities` before and after progress changes to make sure that Trakt is updating it correctly.

I'd also recommend testing via the TMDbHelper add-on itself `TMDbHelper > Trakt > In-Progress Movies` rather than using a widget. That way all you need to do to refresh it is back out and open a different folder and then reopen the in-progress folder.

Lastly, if the sync/lastactivities is definitely updating after you watch something, AND you're definitely logging the correct sync/playback/movies path, AND the sync/playback/list is definitely updating correctly, AND you're using the list inside TMDbHelper not a widget, AND it's still not updating correctly THEN the only thing I can think is that something got corrupted in the cache, in which case:

- Delete the Trakt cache from `TMDbHelper Settings > Expert > Delete Cache` and then restart Kodi
- Logout from Trakt and then reauthenticate via `TMDbHelper Settings > Accounts`

**Comment by ghost** [comment] 2022-01-17 17:47
Only been playing with a couple of movies at a time - all have been fully watched when receiving the No Response! message. Yeah, I've definitely been using the right right command you gave me. I followed your instructions (including clearing trakt cache, rebooting, logging out of trakt) but still the same result- watched movie is also still present in tmdb heper in-progress movies (addon, not widget). I've attached output of both sync/playback/movies & sync/last_activities at two different resume points (59m33s & 1hr 52m) and also sync/last_activities when the movie has finished (sync/playback/movies still gives no response message at this point). Dunno if this helps or not, but I didn't think the timings were matching. Anyway, if you're out of ideas after this, that's fine!

[tmdbhelper_trakt_output.txt](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/files/7883852/tmdbhelper_trakt_output.txt)

**Comment by jurialmunkey** [comment] 2022-01-17 21:58
Thanks! That actually helps a lot. I'm fairly certain I know what the issue is now (I hope!). It just didn't click for me at first that you had absolutely no items left. And yes, it looks like the paused_at value _is_ updating correctly so that wasn't the issue.

I'm fairly sure it is because I setup the sync cache in TMDbH to fallback to the previously cached version if Trakt provides no response. Which makes a lot of sense for watched data because it means that even if Trakt is down won't lose watched indicators and episode counts - but makes far less sense for a list that needs to be up-to-date like play progress.

I should've got a Kodi log from you because that would've said something like "No response for sync_response.syncprogressmovies Attempting fallback... success!" which would've made it obvious to me.

Anyway please try 4.5.3 as I think that _should_ hopefully fix the issue finally.

**Comment by ghost** [comment] 2022-01-17 22:31
Ah, great work jurialmunkey - that's fixed it! Appreciate you taking the time. Bit skint at the moment but hopefully you can buy yourself a couple of pints/ coffees from my small donation. You've created something me and my family use on a daily basis so it's long overdue anyway. Thanks again.

**Comment by jurialmunkey** [comment] 2022-01-18 08:05
> Ah, great work jurialmunkey - that's fixed it! Appreciate you taking the time. Bit skint at the moment but hopefully you can buy yourself a couple of pints/ coffees from my small donation. You've created something me and my family use on a daily basis so it's long overdue anyway. Thanks again.

Ah, that was you! Thanks so much! Will definitely be enjoying a couple of beers.

And thanks for taking the time to work through the issue with me. I have far too many half watched movies on my Trakt list to have ever worked out the caching issue on my own.

**Closed as completed by jurialmunkey** 2022-01-18 08:05 UTC
