### ISSUE TITLE
Constant error with themoviedb.helper

### ISSUE THREAD

**Issue by ZedeN1** [jurialmunkey/plugin.video.themoviedb.helper#376] opened 2020-11-21 22:26 UTC
Keep getting this error constantly, basically on every single change in view (going from movies to shows, from shows to video addons etc). 

Full log on [pastebin](https://pastebin.com/9X7Mn1j0).

Running on Kodi version 18.7 on Raspberry Pi 4B.
Using latest Arctic Horizon 0.5.52
Using plugin.video.themoviedbhelper 4.0.10

``` php
2020-11-22 00:18:18.858 T:2303570128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: implement_array_function method already has a docstring
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 5, in <module>
                                                from resources.lib.script.router import Script
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 26, in <module>
                                                from resources.lib.monitor.images import ImageFunctions
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/monitor/images.py", line 10, in <module>
                                                from PIL import ImageFilter, Image  # TODO: Try Import in-case no PIL and don't use funcs
                                              File "/usr/lib/python2.7/dist-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
                                                from . import core
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 40, in <module>
                                                from . import multiarray
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/multiarray.py", line 12, in <module>
                                                from . import overrides
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/overrides.py", line 46, in <module>
                                                """)
                                            RuntimeError: implement_array_function method already has a docstring
                                            -->End of Python script error report<--
```

**Comment by drinfernoo** [comment] 2020-11-21 22:35
You need to update TMDbHelper. You're on a very old version.

**Comment by ZedeN1** [comment] 2020-11-21 22:53
Exact same issue on 4.0.51 with slightly different error:

``` php 2020-11-22 00:49:40.275 T:2710565072   ERROR: GetDirectory - Error getting include
2020-11-22 00:49:44.345 T:1769992400   ERROR: Previous line repeats 1 times.
2020-11-22 00:49:44.345 T:1769992400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: implement_array_function method already has a docstring
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 5, in <module>
                                                from resources.lib.script.router import Script
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 26, in <module>
                                                from resources.lib.monitor.images import ImageFunctions
                                              File "/home/pi/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/monitor/images.py", line 10, in <module>
                                                from PIL import ImageFilter, Image  # TODO: Try Import in-case no PIL and don't use funcs
                                              File "/usr/lib/python2.7/dist-packages/PIL/ImageFilter.py", line 23, in <module>
                                                import numpy
                                              File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
                                                from . import core
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 40, in <module>
                                                from . import multiarray
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/multiarray.py", line 12, in <module>
                                                from . import overrides
                                              File "/usr/lib/python2.7/dist-packages/numpy/core/overrides.py", line 46, in <module>
                                                """)
                                            RuntimeError: implement_array_function method already has a docstring
                                            -->End of Python script error report<--
2020-11-22 00:49:55.521 T:2471424208   ERROR: Previous line repeats 4 times.
''`

**Comment by jurialmunkey** [comment] 2020-11-21 22:55
Duplicate of these two issues: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/301 https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/244

It is due to your Linux distribution overriding numpy module with its own version.

Solution is here: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/244#issuecomment-639737411

**Comment by ZedeN1** [comment] 2020-11-21 23:06
Thanks that fixed it!

**Closed** 2020-11-21 23:18 UTC
