### ISSUE TITLE
Live TV artwork

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/plugin.video.themoviedb.helper#624] opened 2022-01-14 17:10 UTC
Hi Jurialmunkey. Recently subscribed to Schedules Direct for live tv epg data, mainly for the programme art it provides. However, I notice that a lot of the artwork is overridden by AH (poster on programme info screen) and is often incorrect. I tried turning all fanart tv options off in tmdb helper but didn’t make any difference- something else is taking priority over schedules direct artwork and trying to match programme data. Do you have any ideas? On a side note, would love to see programme artwork displayed on AH2’s epg, similar to Estuary 🤞. Thanks for your work on this skin, absolutely awesome.

**Comment by jurialmunkey** [comment] 2022-01-14 21:39
It's the skin preferencing tmdbhelper artwork and info. The pvr lookups in TMDbH assume that everything is a tv show so movies end up with wrong data. I haven't found a reliable way to differentiate and I don't have a working pvr at the moment to test because where I currently live the over the air reception is very poor.

I'll add an option to disable TMDbH pvr lookups.

**Comment by ghost** [comment] 2022-01-14 22:14
Ah thanks man, appreciate it. Interestingly, schedules direct artwork often remains for movies, with more incorrect matches happening for tv shows. An example would be BBC Breakfast News displaying The Big Breakfast (a uk show that aired many years ago). Also wonder if the display area could be fit to artwork size, although I suspect not. Maybe I can play with tv grabber to get full poster-sized artwork instead. Attached an image as an example. Thanks. 
![08F5614F-5651-4689-8B22-40AF0770ACB9](https://user-images.githubusercontent.com/62660160/149591798-0f37fbea-bf9f-4cd7-a73f-c56a38b51402.jpeg)

**Comment by jurialmunkey** [comment] 2022-01-14 23:42
Yeah the PVR matching in general is difficult because the base information often isn't great. Having something like first air year improves tv matching a lot. The problem is generally PVR only has the _episode_ year, not the show, so the matching using that is a lot fuzzier. Then add in lots of shows with similar names such as Breakfast shows and it really isn't great.

Really, I should probably disable it altogether until I have a better approach for it. It's always been a bit of an "alpha" feature that I intended to improve but has been neglected because I don't currently have a working PVR setup to test as I go.

On the artwork size - the square keep aspect is forced by the skin, so you won't be able to get a poster. 

A lot of the PVR clients in Kodi are bad at separating artwork into types, which means what might work for one PVR client ends up not working for another. So I just stick to a safe square with a border to make sure it works for all. I only use poster aspect for artwork coming from TMDbH because I know it definitely is a poster and not some other artwork incorrectly dumped into the poster artwork type. 

I think maybe Estuary on Matrix has some improvements on the PVR artwork front, so hopefully I'll be able to pull some of those improvements into AH2 when I eventually get to skinning the PVR windows.

**Comment by ghost** [comment] 2022-01-14 23:51
That’s good to know - thanks for the response, and really looking forward to AH2!

**Comment by jurialmunkey** [comment] 2022-01-15 01:17
@Tee77 - Can you test latest git version (v4.4.70)? I think this should improve PVR matching quite significantly. It uses a multisearch so it should work with movies too now. The matching is much stricter with this method - so the title has to match exactly with TMDb (I strip out any special characters and make the query all lower case to avoid very slight differences e.g. "Terminator 2: Judgement day" will match "Terminator 2 Judgement Day" but otherwise the matching is strict to avoid false positives).

**Comment by ghost** [comment] 2022-01-15 02:43
Wow, you really don’t mess about! That’s working really well now. Breakfast show for example now leaves schedules direct artwork in place, and all movies are being pulled in properly, with correct cast list. Super impressed, thanks man!

**Comment by ghost** [comment] 2022-01-15 02:50
FYI I noticed one example where The Pink Panther movie is pulling in cartoon artwork for a tv series I presume  (overriding schedules direct artwork), but I guess that’s what you referred to before re. the difficulty distinguishing between TV/ Movies. However, almost everything else is working really well.

**Comment by jurialmunkey** [comment] 2022-01-15 04:52
> FYI I noticed one example where The Pink Panther movie is pulling in cartoon artwork for a tv series I presume (overriding schedules direct artwork), but I guess that’s what you referred to before re. the difficulty distinguishing between TV/ Movies. However, almost everything else is working really well.

Yeah those types of scenarios are tricky where there's multiple items with the same name - and The Pink Panther is particularly difficult because there's a tvshow and also a remake movie all with the same name. I do check for season/episode numbers, so if the PVR backend sets those then TMDbH will assume it's a tvshow -- but it's trickier to determine if something is _not_ a tvshow and definitely a movie.

I might see if I can use the PVR genre types to help differentiate movies -- though with something like Pink Panther there's still the issue of which version of the movie - the original or the remake!

**Comment by ghost** [comment] 2022-01-15 07:09
Yeah I hear what you’re saying. Interestingly, I’ve recently moved to tvheadend 4.3 (currently the ‘unstable’ version but recommended by devs to use over the now very outdated stable 4.2) which has an option to ‘use category instead of genre’. This overwrites genres with a list of categories for each programme, including ‘movie’, ‘feature film’, ‘episode’, ‘series’ and ‘show’. I’m guesssing this could help with fine tuning, but also recognise that this may not work for other pvr setups so is probably not an option. Just thought it worth mentioning. Looking forward to any developments, but the change you’ve made has already made a real difference. 😁

**Comment by jurialmunkey** [comment] 2022-05-22 03:48
I've tried a few different approaches but all had issues. 

Checking against genre ended up being a bit of a bust as it is too inconsistent between different services and regions. Also, really need the subcategory designation and that's not available in channels view (only guide) so the inconsistency isn't worth it.

I think it's probably as good as it is going to get so I'm going to close this issue.

**Closed as completed by jurialmunkey** 2022-05-22 03:48 UTC
Labels: bug, enhancement
